### ISSUE TITLE
Python bundled in Sire

### ISSUE THREAD

**Issue by ggerogiokas** [michellab/Sire#11]
Hi,

Just suggesting that when you compile the python3.3 in the bundle for Sire that you add the --with-zlib option into cmake.  list( APPEND PYTHON_OPTIONS "--with-zlib" )  I am getting Python version without 
zlib capability so I can't install setuptools.

Thanks,
George

**Comment by ggerogiokas** [comment]
Specifically I get the following issue when I try to install setuptools with the python3.3 in Sire:
zipimport.ZipImportError: bad local file header in /usr/users/gerogiokas/sire.app/bundled/lib/python3.3/site-packages/setuptools-0.9.8-py3.3.egg

Thanks,
George

**Comment by ppxasjsm** [comment]
Hey,
try the following. Replace in wrapper/bundeled/setuptools.tar.gz, with the latest version of setuptools from here:
https://pypi.python.org/pypi/setuptools

I had a similar problem. This is fixed in the devel branch, but hasn't been committed down to master yet. Let me know if this helps. 

-Toni

**Comment by ggerogiokas** [comment]
Thanks,
Yea I will try that I thought I need setuptools to get pip but apparently I don't at the moment.
But yes I will keep not about the new setuptools.

Thanks,
George
