### ISSUE TITLE
Compile_sire issue on Mac OSX using latest devel

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#116]
Is the `compile_sire.sh` script meant to work for Mac OSX? 
It does not seem to work with the current devel version:

```./compile_sire.sh 
Where would you like to install Sire? [/Users/toni_brain/sire.app]: /Users/toni_brain/sire.app_dev
Installing into directory '/Users/toni_brain/sire.app_dev'
64 bit processor
64 bit operating system
** Unpacking miniconda into /Users/toni_brain/sire.app_dev... **
** bash build/miniconda.sh -b -p /Users/toni_brain/sire.app_dev **
** FATAL **
** Cannot find /Users/toni_brain/sire.app_dev/bin/python **
** Something went wrong with the miniconda install! **
** Remove /Users/toni_brain/sire.app_dev, then run compile_sire.sh --clean, then try again **
```

Looks like the install prefix is not set properly and creating the target directory.

**Comment by ppxasjsm** [comment]
Oh compiler versions are: 
``` g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

Though I guess I didn't even get to that point yet.

**Comment by chryswoods** [comment]
Thanks. This is because the http page for miniconda now redirects to https, and wget on OS X doesn't have https support. wget exits with status 0, meaning that compile_sire.sh thought that miniconda was downloaded properly, and then got confused when no python was unpacked.

The fix was to point to https directly in compile_sire.sh (just done and pushed now), so that wget fails, and exits with a non-zero code. This then allowed the curl call to take over and download (curl does have https on OS X). This is all working now.
