### ISSUE TITLE
runtime error after updating sire

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#127]
After switching branches, updating source and recompiling the code via make install in corelib and wrapper I have run a number of times in this runtime error

julien@ubuntu:/mnt/hgfs/sims/nutlins/runs-12w-26w-10ns/Nutlin3a/bound/run001/vanish/output$ ~/sire.app/bin/somd-standardstatecorrection -C  ../input/sim.cfg -t ../input/SYSTEM.top -r lambda-1.000/traj000000001.dcd -s 10

**********************************************************
Something went wrong with the simulation. Here's the error
**********************************************************

Exception 'SireError::file_error' thrown by the thread 'master'.
Cannot find the file or directory "pkgs/sire-2016.3.1/share/Sire" in the Sire install directory "/home/julien/sire.app" (/home/julien/sire.app/pkgs/sire-2016.3.1/share/Sire).

Here the problem is that my binary contains the directory /home/julien/sire.app/pkgs/sire-2016.1.0/
but the code thinks (rightly) that it is running 2016.3.1

It looks like running make install in corelib and wrapper is unsafe if there has been a change in release version. 

Is there a way to avoid doing a clean binary install? It's not super great to have to delete my ~/sire.app, recompile from scratch, and then add again all dependencies via pip/conda.

**Comment by jmichel80** [comment]
Weird, I deleted ~/sire.app, then ran ./compile-sire.sh to do a fresh install. 
I still end up with the same runtime error because I have the folder ~/sire.app/pkgs/sire-2016.1.0
renaming this folder to sire-2016.3.1 does let the code run but messes up the build folders. 

My conclusion so far is that it is necessary to delete the $SIRE_SRC/build folder before running ./compile-sire.sh IF the sire version has changed. This is perhaps due to the value of cmake variable SIRE_INSTALL_PREFIX  /home/julien/sire.app/pkgs/sire-2016.3.1.

Considering it takes half a working day to do a full build from scratch (on my laptop VM), and get to the stage where I can run somd again, is there a way to avoid this extra work whenever we change the version of the code?

**Comment by chryswoods** [comment]
Sorry - yes it is necessary to remove the build directory and your existing sire.app directory whenever the version number changes. This is annoying, but is unavoidable because Sire installs into a pkgs/sire-20X.Y.Z directory. The version number is part of the directory name as following the conda standard. The installation path is baked into the libraries via RPATH/ORIGIN, so a recompilation from scratch is necessary if this changes. The complete reinstall is also required to prevent weird bugs when you link against old files that were in an old pkgs/sire-20X.Y.Z directory.

I know recompiling from scratch is painful. It should only happen 3-4 times a year when we change the version number. You can avoid it by editing the CMakeFiles.txt and changing the version number back.
