### ISSUE TITLE
temporarily switching between branches triggers a full rebuild 

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#130]
Hi,

I have run into this odd behavior. I was working on feature_standardstategen and had an updated binary. I checked out feature_ljtail to inspect some files not on feature_standardstategen. I went back to feature_standardstategen and added new python code in wrapper/Tools and wrapper/python/scripts. 
I then ran make install in build/wrapper, expecting to only install the added python code. 
However a full build seem to have been triggered, so my laptop is hogged for the next hour or so.

I imagine there are a number of reasons that can explain this behavior.  Would be great to have Chris post a clarification so we can bear this mind while developing between branches.

Julien

**Comment by chryswoods** [comment]
There are a very small number of files that trigger a full rebuild, i.e. src/sireglobal.h, src/SireBase/property.h, src/bundled/qtbase.tar.gz etc. These are files on which nearly all of Sire depends. I try to limit changes to these files because they do cause a big rebuild. My guess is that there had been changes in one of these files between the two versions. Because the file changed in the two checkouts, this triggers a new rebuild with make. 

Looking deeper, you can see all of the changes between feature_standardstategen and feature_ljtail by looking here <https://github.com/michellab/Sire/compare/feature_ljtail...feature_standardstategen>. There are a *large* number of changes, so I am not surprised that some of the key files that trigger a full rebuild have changed (the differences span back to November 2015). If you are comparing code that is separated by so much time, then it is more efficient to manually check out two branches on your computer and work with them independently. This will avoid changing any of the key files that trigger a rebuild.

**Comment by jmichel80** [comment]
That makes sense. I figured it would be more effective to pick up the few files from feature_ljtail I needed to add to feature_standardstategen, and then plan to merge feature_standardstategen again into devel. This because feature_standardstategen is a recent fork of devel, hence the move. 

Good advice to checkout separate branches to avoid triggering rebuilds. Thanks !

**Comment by chryswoods** [comment]
No problem :-). Full rebuilds are really painful, and I do need to work out how to create shortcuts.
