### ISSUE TITLE
current devel verison does not run free energy code

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#136]
I compiled the current devel version of Sire trying to run a very basic simulation.
I get the folllowing error:

```
Starting /home/ppxasjsm/dev_sire.app/bin/somd-freenrg: number of threads equals 32
Traceback (most recent call last):
  File "/home/ppxasjsm/dev_sire.app/pkgs/sire-2016.3.1/share/Sire/scripts/somd-freenrg.py", line 146, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/home/ppxasjsm/dev_sire.app/lib/python3.6/site-packages/Sire/Tools/__init__.py", line 172, in inner
    retval = func()
  File "/home/ppxasjsm/dev_sire.app/lib/python3.6/site-packages/Sire/Tools/OpenMMMD.py", line 1547, in runFreeNrg
    moves = setupMovesFreeEnergy(system, ranseed, gpu.val, lambda_val.val)
  File "/home/ppxasjsm/dev_sire.app/lib/python3.6/site-packages/Sire/Tools/OpenMMMD.py", line 1117, in setupMovesFreeEnergy
    Integrator_OpenMM = OpenMMFrEnergyST(molecules, solute, solute_hard, solute_todummy, solute_fromdummy)
NameError: name 'OpenMMFrEnergyST' is not defined
srun: error: node010: task 0: Exited with exit code 1
```
I haven't touched any of this recently. Any idea what could be going wrong here?

**Comment by ppxasjsm** [comment]
And even better:
```
In [1]: import Sire
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-a6a0571da4c9> in <module>()
----> 1 import Sire

/home/ppxasjsm/dev_sire.app/lib/python3.5/site-packages/Sire/__init__.py in <module>()
    182 #ensure that the SireQt and SireError libraries are loaded as
    183 #these are vital for the rest of the module
--> 184 import Sire.Qt
    185 import Sire.Error
    186 import Sire.Config

/home/ppxasjsm/dev_sire.app/lib/python3.5/site-packages/Sire/Qt/__init__.py in <module>()
     17 # been loaded
     18 
---> 19 from Sire.Qt._Qt import *

ImportError: libSireError.so.2016: cannot open shared object file: No such file or directory
```

**Comment by jmichel80** [comment]
I have no idea what's going on but i did recently check out and build from scratch feature-standardstategen on my laptop and section6 . Might be a temporary fix for you?

**Comment by ppxasjsm** [comment]
Ok I used your slightly modified version and that seems to work now.

**Comment by chryswoods** [comment]
The error "ImportError: libSireError.so.2016: cannot open shared object file: No such file or directory" indicates that the RPATH or ORIGIN for _Qt.so or _Error.so may be incorrect. This can be caused by many things, i.e.

* Updated the version number of Sire, e.g. 2016.2 to 2016.3, which puts libraries into slightly different paths
* Moving of directories or libraries after they have been compiled, e.g. tar up and untar the files
* Gradual breakage caused by partial recompilations, rather than properly compiling from scratch using compile_sire.sh. Expensive as it is, a clean run of compile_sire.sh is the best way to make sure that everything is compiled in the right location and pointing at the right thing.
