### ISSUE TITLE
devel) how to pass a dictionary as a command line argument?

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#149]
Hi,

somd no longer works now that I updated to devel. 
I get this runtime error

Create the System...
Selecting dummy groups
Starting /home/julien/sire.app/bin/somd-freenrg: number of threads equals 32
Traceback (most recent call last):
  File "/home/julien/sire.app/pkgs/sire-2016.3.1/share/Sire/scripts/somd-freenrg.py", line 146, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/home/julien/sire.app/lib/python3.5/site-packages/Sire/Tools/__init__.py", line 172, in inner
    retval = func()
  File "/home/julien/sire.app/lib/python3.5/site-packages/Sire/Tools/OpenMMMD.py", line 1527, in runFreeNrg
    system = setupDistanceRestraints(system, restraints=restraints)
  File "/home/julien/sire.app/lib/python3.5/site-packages/Sire/Tools/OpenMMMD.py", line 614, in setupDistanceRestraints
    dic_items = list(distance_restraints_dict.val.items())
AttributeError: 'str' object has no attribute 'items'
srun: error: node011: task 0: Exited with exit code 1

The issue is that the input config file for this simulation contains the following keyword

distance restraints dictionary = {(10,817):(5.5,10.0,1.0),(10,1454):(6.5,10.0,1.0),(14,891):(5.0,10.0,1.0),(14,1454):(7.0,10.0,2.0),(31,1515):(5.5,10.0,1.0),(31,1454):(5.0,10.0,1.0),(43,1515):(5.0,10.0,1.0),(43,817:(5.5,10.0,1.0)}

Up until the update this line was interpreted as a python dictionary, but it is now parsed as a string.

This Parameter is defined around l164 in OpenMMMD.py.
https://github.com/michellab/Sire/blob/devel/wrapper/Tools/OpenMMMD.py

How should we parse dictionaries from now on?

**Comment by Steboss** [comment]
Hi Julien

One way could be "ast"
ast is a pyton module, which is able to transform string to dictionary
for example:
```
import ast

my_dictionary = ast.literal_eval(my_string)
```

This trick was used also in StandardState.py script

**Comment by jmichel80** [comment]
@steboss yes I could also change the code to assume that my input was a string and type

dict(distance_restraints_dict)

But I want to establish first why the parser has changed behaviour, and what types can we safely expect the parser to return from a config file

**Comment by chryswoods** [comment]
@jmichel80 - the parser still works. The problem is that your string has an error

```
distance restraints dictionary = {(10,817):(5.5,10.0,1.0),(10,1454):(6.5,10.0,1.0),(14,891):(5.0,10.0,1.0),(14,1454):(7.0,10.0,2.0),(31,1515):(5.5,10.0,1.0),(31,1454):(5.0,10.0,1.0),(43,1515):(5.0,10.0,1.0),(43,817:(5.5,10.0,1.0)}
```

should be

```
distance restraints dictionary = {(10,817):(5.5,10.0,1.0),(10,1454):(6.5,10.0,1.0),(14,891):(5.0,10.0,1.0),(14,1454):(7.0,10.0,2.0),(31,1515):(5.5,10.0,1.0),(31,1454):(5.0,10.0,1.0),(43,1515):(5.0,10.0,1.0),(43,817):(5.5,10.0,1.0)}
```

(you were missing the ')' after '817' in the last item. This meant that the "exec" in python failed, so the parser then thought that this must be a string. It then parsed the item as a string. As I've said before, the parser is really terrible and doesn't have good error or type checking. Currently it greedily tries to parse without throwing an error (i.e. it will parse broken values like yours as strings if everything else fails). The solution is for me to add a "type" clause to Parameter so that the parser is able to know and check that the value has the right type. This is not as simple as it sounds. It will be solved as part of BioSimSpace ;-).

For reference, here is the parsing code (in https://github.com/michellab/Sire/blob/devel/wrapper/Tools/__init__.py, line 131)

```python
        for key in keys:
            value = str(params[key]).lstrip().rstrip()

            # execute the parameter, so that it is parsed
            try:
                exec("_pvt_val = %s" % value, globals())
            except:
                # parsing failed, so see if this is a "value unit" type variable
                _pvt_words = value.split()

                _pvt_ok = False

                if len(_pvt_words) == 2:
                    # try the form N * unit
                    try:
                        exec("_pvt_val = %s * %s" % (_pvt_words[0],_pvt_words[1]), globals())
                        _pvt_ok = True
                    except:
                        pass
                else:
                    # maybe this is a string?
                    try:
                        exec("_pvt_val = \"%s\"" % value.replace("\\","\\\\"), globals())
                        _pvt_ok = True
                    except:
                        pass

                if not _pvt_ok:
                    broken_parameters.append( (key, value) )

            params[key] = _pvt_val
            print("%s == %s" % (key,params[key]))
```

**Comment by chryswoods** [comment]
p.s. In debugging I have added this as a unit test to test_parser.py (https://github.com/michellab/SireUnitTests/blob/devel/unittests/Tools/test_parser.py and https://github.com/michellab/SireUnitTests/blob/devel/unittests/Tools/configfile).

I hadn't seen that you were passing dictionaries and am surprised and happy that it works (mostly). If you want to ensure that the parser always works for data types that you use, then please add them into this unit test so that they are captured whenever I update the parser. As I said above, I need to rework the parser a lot but still need to ensure that it is backwards compatible.

**Comment by jmichel80** [comment]
Thanks chris, I will make sure to update the unit test if I pass other types in the future
