### ISSUE TITLE
Installing on OSX

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#171]
I have yet encountered another issue with the installation. 

Trying to install a fresh version of the devel branch. Pulled the latest version of it and simply executed the compile_sire.sh script. 

But I get the following error. 
```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: /Users/toni_brain/sire.app_dev/pkgs/sire-2017.2.0/bundled/lib/libcpuid.dylib (No such file or directory)
CMake Error at src/bundled/install_cpuid.cmake:80 (message):
  Cannot find CPUID library
  /Users/toni_brain/sire.app_dev/pkgs/sire-2017.2.0/bundled/lib/libcpuid.dylib.
  Error with compile?
Call Stack (most recent call first):
  CMakeLists.txt:737 (include)
```

I am running macos Sierra 10.12.6. 
I did an update recently. Before that I didn't have any issues compiling, but amongst other things all my symlinks to cmake had also been removed with the update.

**Comment by ppxasjsm** [comment]
After some googling I am still struggling with this. it seems to struggle to install the bundled libcpid library. 

Can it be that compiler versions are wrong?
```
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
```

**Comment by chryswoods** [comment]
Ah - the dreaded libcpuid.dylib compile problem. I see this a lot when things break, i.e. when Xcode development tools are not installed correctly, or if there is something broken with the compilers or install paths. This is because libcpuid is the first bundled library that is compiled, so it is the first to break if there is a major problem.

Common causes of the problem are;

* The version number of Sire has changed (e.g. 2017.1.0 to 2017.2.0). This means that Sire is installed into a different conda directory (pkgs/sire-2017.2.0 versus pkgs/sire-2017.1.0), which breaks the library symlinks. The build scripts in your build/corelib/build_bundled directory try to install libraries into the old pkgs/sire... directory, while the cmake script is looking in the new pkgs/sire... directory for the library. The solution to this problem is that you have to remove your sire.app, build/corelib and build/wrapper directories every time the version number changes, and recompile everything from scratch. 

* The compiler is not properly creating the libcpuid.dylib library. This can happen if cmake has set the compiler incorrectly or it cannot find system libraries that are needed to link libraries. You can get the error by changing into the Sire/build/corelib/build_bundled/libcpuid directory and running "make" and "make install" directly there. See if there are any error messages or if libcpuid.dylib goes to the wrong location.

* The compiler/system decides to ignore the library naming convention and calls libcpuid.dylib something else. This is more common on linux, e.g. some distros used libcpuid.X.Y.so without providing the symlink to libcpuid.so. I've mostly fixed these problems, but am always happy to see more ;-)

* Xcode is not properly installed, or needs to have the license accepted. I see this more when compiling the bundled Qt5. This happens after upgrading OS X or XCode. If you change into the Sire/build/corelib/build_bundled/qtbase directory and run configure and make, you will see this bail out with "You need to accept the Xcode license. Run xcodeselect ....". The instruction to run xcodeselect only worked on older OS Xs, so I normally have to google a bit to find the correct command for the version of OS X I upgraded to.

* You have upgraded OS X to a version that the libraries don't currently support. A lot of things in the libraries use hardcoded OS X version numbers (particularly Qt!!!). This means that you can get a lot of bundled library compile errors when you upgrade OS X to a new version (as I plan to do for High Sierra over this weekend). I fix these using the qtpatch.tgz that I ship with the bundled qtbase.tgz, so hopefully you rarely have to see these. It is a constant source of annoyance whenever a new OS X version comes out...

**Comment by ppxasjsm** [comment]
The latest fix was actually running: `xcode-select --install`. In order to properly install the commandline tools of xcode after the upgrade, incase someone else runs into the same issue. 

Install works fine with:
```
cc --version
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
And Sierra version:10.12.6
