### ISSUE TITLE
error despite running to completion

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#180]
Hi,

I have periodically been getting the following error:

```
Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads

Thread 0x00007fca14a98700 (most recent call first):
  File "/home/ppxasjsm/sire.app_dev/lib/python3.5/site-packages/Sire/__init__.py", line 256 in _uploadUsageData
  File "/home/ppxasjsm/sire.app_dev/lib/python3.5/threading.py", line 862 in run
  File "/home/ppxasjsm/sire.app_dev/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/home/ppxasjsm/sire.app_dev/lib/python3.5/threading.py", line 882 in _bootstrap

Current thread 0x00007fca1a205740 (most recent call first):
Aborted (core dumped)
```

The python sire scripts seem to execute fine though.

**Comment by lohedges** [comment]
Hi Toni,

Do you have an example script that triggers this error?

According to [this](https://stackoverflow.com/questions/45267439/fatal-python-error-and-bufferedwriter) Stack Overflow link it looks like it's a problem with the interpreter exiting before all of the threads have finished their work. This means that the `stdout` buffer has already been closed.

The following python code (taken from the above link) will periodically have this problem when run with python 3.X:

```python
from _thread import start_new_thread
import time

def start():
    for i in range(10):
        print("SPAM SPAM SPAM!")

for i in range(10):
    start_new_thread(start, ())

time.sleep(0.0001)
print("main thread exited")
```
By waiting for the threads to finish the problem is avoided (here this is achieved by calling `join` from the main thread):

```python
from threading import Thread
import time

def start():
    for i in range(10):
        print("SPAM SPAM SPAM!")

# create a thread list (you'll need it later)
threads = [Thread(target=start, args=()) for i in range(10)]

# start all the threads
for t in threads:
    t.start()
# or [t.start() for t in threads] if you prefer the inlines

time.sleep(0.0001)

# wait for threads to finish
for t in threads:
    t.join()
# or [t.join() for t in threads] for the inline version

print("main thread exited")
``` 
Cheers,
Lester

**Comment by ppxasjsm** [comment]
Um, it is random. I haven't figured out when it triggers and when it doesn't. For example out of the tutorial: http://chryswoods.com/intro_to_mc/part2/intro.html make_l7n.py has triggered this, but sometimes runs fine. I'll see if I can find a pattern.

**Comment by lohedges** [comment]
Yes, it will be totally random when it occurs. The problematic script that I mentioned above only triggers the error about 10% of the time (on my machine anyway).

Looking more closely at your original error message, it looks like the problem is in:

```bash
/home/ppxasjsm/sire.app_dev/lib/python3.5/site-packages/Sire/__init__.py", line 256 in _uploadUsageData
```

This is Christopher's usage tracker for Sire, which indeed uses the python threading module. As a quick fix you could disable usage analytics by adding the following to your environment variables:

```
export SIRE_DONT_PHONEHOME=1
export SIRE_SILENT_PHONEHOME=1
```
(You only need the second if you want to hide the message too.)

I added these shortly after I started working on Sire (since I don't want to clutter the stats while developing) so that's probably why I've not run across the issue that you've reported.

I'll turn the reporting back on and see if I can track down the problem in `_uploadUsageData`.

Cheers.

**Comment by ppxasjsm** [comment]
In the mean time i'll turn it off...

**Comment by lohedges** [comment]
I can't seem to reproduce the error at my end but it's possible that we need to add `_thread.join()` to the very bottom of `~sire.app/lib/python3.5/site-packages/Sire/__init__.py`.

Feel free to add this in your version to see if it makes any difference.

**Comment by ppxasjsm** [comment]
I'll try this and report back.

**Comment by chryswoods** [comment]
Yes, I occasionally see this error too. For some random reason, the upload of usage tracking takes too long, which means that the thread gets killed if the program exits beforehand. It is a confusing error, as the rest of the program is correct. The solution is not to use _thread.join(), as this would cause the program to randomly appear to freeze at the end of the program if the upload takes far too long. The correct solution is for the thread to be silently killed (i.e. no error output). Is there a way to silently kill python threads?

**Comment by chryswoods** [comment]
I will close this issue as the problem is know but there isn't an immediate fix. We can reopen if it becomes annoying.
