### ISSUE TITLE
QT error with 18.1 on Ubuntu 18.04

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#204]
I have been playing with the installation of the latest sire version a bit. 
The install on a vanilla 18.04 system seems to work ok. (Install cmake, git and build-essential through apt)
But trying to then run the test I get the following error:
```
Starting /home/manager/sire.app/bin/sire_test: number of threads equals 4
Traceback (most recent call last):
  File "/home/manager/sire.app/pkgs/sire-2018.1.1/share/Sire/scripts/sire_test.py", line 5, in <module>
    from Sire import try_import
  File "/home/manager/sire.app/lib/python3.5/site-packages/Sire/__init__.py", line 184, in <module>
    import Sire.Qt
  File "/home/manager/sire.app/lib/python3.5/site-packages/Sire/Qt/__init__.py", line 19, in <module>
    from Sire.Qt._Qt import *
ImportError: /usr/lib/x86_64-linux-gnu/libboost_python.so: undefined symbol: PyClass_Type

```

I know there have been numerous QT errors in the past. Not really sure what to make of this one though.

**Comment by chryswoods** [comment]
This error is because Sire is finding and using libboost_python.so in /usr/lib (installed on the system), rather than the libboost_python.so that is compiled and installed into Sire (sire.app/lib/libboost_python.so). The $ORIGIN_PATH is set so that this should not happen, so something went wrong with compilation, or something is wrong with $ORIGIN interpretation at runtime.

Test 1 - is this a compilation error or runtime error?
Could you download and install 2018.1.1 and check to see if the same error appears when you run sire_test. If this works, then it is a compilation error. If it doesn't, then it is a runtime error.

Test 2 - What is the library path?
Can you run "ldd sire.app/bin/sire_python" for both your compiled sire.app and also for the 2018.1.1 install? This will show the libraries that are being found at runtime for both. They should be the same if compilation worked. This will show us which libraries are being found. The only system libraries should be related to Linux, e.g. libc, ld_linux etc. Everything else should be found from the sire.app directory.

**Comment by ppxasjsm** [comment]
Installing from binary:
/home/manager/sire.app_18.1/bin/sire_test
Illegal instruction (core dumped)


Test 2:
For the compiled version:
```
linux-vdso.so.1 (0x00007ffc7b0da000)
	libpython3.5m.so.1.0 => /home/manager/sire.app/bin/../lib/libpython3.5m.so.1.0 (0x00007f1da37ef000)
	libSireCluster.so.2018 => /home/manager/sire.app/bin/../lib/libSireCluster.so.2018 (0x00007f1da35bd000)
	libSireBase.so.2018 => /home/manager/sire.app/bin/../lib/libSireBase.so.2018 (0x00007f1da32f9000)
	libSireStream.so.2018 => /home/manager/sire.app/bin/../lib/libSireStream.so.2018 (0x00007f1da30c0000)
	libSireError.so.2018 => /home/manager/sire.app/bin/../lib/libSireError.so.2018 (0x00007f1da2ea3000)
	libQt5Core.so.5 => /home/manager/sire.app/bin/../lib/libQt5Core.so.5 (0x00007f1da278d000)
	libtbb.so.2 => /home/manager/sire.app/bin/../lib/libtbb.so.2 (0x00007f1da2551000)
	libstdc++.so.6 => /home/manager/sire.app/bin/../lib/libstdc++.so.6 (0x00007f1da2217000)
	libgcc_s.so.1 => /home/manager/sire.app/bin/../lib/libgcc_s.so.1 (0x00007f1da2005000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1da1c14000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1da19f5000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1da17f1000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f1da15ee000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1da13e6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1da1048000)
	libSireMaths.so.2018 => /home/manager/sire.app/bin/../lib/./libSireMaths.so.2018 (0x00007f1da0d72000)
	libSireUnits.so.2018 => /home/manager/sire.app/bin/../lib/./libSireUnits.so.2018 (0x00007f1da0b3a000)
	libSireID.so.2018 => /home/manager/sire.app/bin/../lib/./libSireID.so.2018 (0x00007f1da092d000)
	libcpuid.so.10 => /home/manager/sire.app/bin/../lib/./libcpuid.so.10 (0x00007f1da071f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1da3ee5000)
	libgsl.so.0 => /home/manager/sire.app/bin/../lib/././libgsl.so.0 (0x00007f1da02f1000)
	libgslcblas.so.0 => /home/manager/sire.app/bin/../lib/././libgslcblas.so.0 (0x00007f1da00b2000)


```
And from the installed binary:
```ldd ~/sire.app_18.1/bin/sire_python
	linux-vdso.so.1 (0x00007ffd233c1000)
	libSirePython.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSirePython.so.2018 (0x00007fd91f0bc000)
	libSquire.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSquire.so.2018 (0x00007fd91eda5000)
	libSireIO.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSireIO.so.2018 (0x00007fd91e81f000)
	libSireAnalysis.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSireAnalysis.so.2018 (0x00007fd91e5b1000)
	libpython3.5m.so.1.0 => /home/manager/sire.app_18.1/bin/../lib/libpython3.5m.so.1.0 (0x00007fd91e0c1000)
	libboost_python.so => /home/manager/sire.app_18.1/bin/../lib/libboost_python.so (0x00007fd91de69000)
	libSireMove.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSireMove.so.2018 (0x00007fd91d99e000)
	libSireCluster.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSireCluster.so.2018 (0x00007fd91d76c000)
	libOpenMM.so => /home/manager/sire.app_18.1/bin/../lib/libOpenMM.so (0x00007fd91cfab000)
	libnetcdf.so.13 => /home/manager/sire.app_18.1/bin/../lib/libnetcdf.so.13 (0x00007fd919c6c000)
	libSireSystem.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSireSystem.so.2018 (0x00007fd9198dd000)
	libSireMM.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSireMM.so.2018 (0x00007fd919119000)
	libSireFF.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSireFF.so.2018 (0x00007fd918d9e000)
	libSireMol.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSireMol.so.2018 (0x00007fd9185f9000)
	libSireVol.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSireVol.so.2018 (0x00007fd918381000)
	libSireCAS.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSireCAS.so.2018 (0x00007fd9180ad000)
	libSireMaths.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSireMaths.so.2018 (0x00007fd917dd0000)
	libgsl.so.0 => /home/manager/sire.app_18.1/bin/../lib/libgsl.so.0 (0x00007fd9179aa000)
	libgslcblas.so.0 => /home/manager/sire.app_18.1/bin/../lib/libgslcblas.so.0 (0x00007fd91776d000)
	libSireBase.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSireBase.so.2018 (0x00007fd9174a3000)
	libSireID.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSireID.so.2018 (0x00007fd917296000)
	libSireUnits.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSireUnits.so.2018 (0x00007fd91705d000)
	libSireStream.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSireStream.so.2018 (0x00007fd916e23000)
	libSireError.so.2018 => /home/manager/sire.app_18.1/bin/../lib/libSireError.so.2018 (0x00007fd916c05000)
	libQt5Core.so.5 => /home/manager/sire.app_18.1/bin/../lib/libQt5Core.so.5 (0x00007fd9164e4000)
	libtbb.so.2 => /home/manager/sire.app_18.1/bin/../lib/libtbb.so.2 (0x00007fd916294000)
	libtbbmalloc.so.2 => /home/manager/sire.app_18.1/bin/../lib/libtbbmalloc.so.2 (0x00007fd916056000)
	libcpuid.so.10 => /home/manager/sire.app_18.1/bin/../lib/libcpuid.so.10 (0x00007fd915e49000)
	libstdc++.so.6 => /home/manager/sire.app_18.1/bin/../lib/libstdc++.so.6 (0x00007fd915b0f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd915771000)
	libgcc_s.so.1 => /home/manager/sire.app_18.1/bin/../lib/libgcc_s.so.1 (0x00007fd91555f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd91516e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd914f4f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd914d4b000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fd914b48000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd914940000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd91f2c4000)
	libmfhdf.so.0 => /home/manager/sire.app_18.1/bin/../lib/./libmfhdf.so.0 (0x00007fd914716000)
	libdf.so.0 => /home/manager/sire.app_18.1/bin/../lib/./libdf.so.0 (0x00007fd91446b000)
	libhdf5_hl.so.100 => /home/manager/sire.app_18.1/bin/../lib/./libhdf5_hl.so.100 (0x00007fd914247000)
	libhdf5.so.101 => /home/manager/sire.app_18.1/bin/../lib/./libhdf5.so.101 (0x00007fd913cb2000)
	libcurl.so.4 => /home/manager/sire.app_18.1/bin/../lib/./libcurl.so.4 (0x00007fd913a3e000)
	libjpeg.so.9 => /home/manager/sire.app_18.1/bin/../lib/././libjpeg.so.9 (0x00007fd913802000)
	libz.so.1 => /home/manager/sire.app_18.1/bin/../lib/././libz.so.1 (0x00007fd9135eb000)
	libssl.so.1.0.0 => /home/manager/sire.app_18.1/bin/../lib/././libssl.so.1.0.0 (0x00007fd913375000)
	libcrypto.so.1.0.0 => /home/manager/sire.app_18.1/bin/../lib/././libcrypto.so.1.0.0 (0x00007fd912f35000)


```

**Comment by lohedges** [comment]
How strange, it looks like the compiled version is missing a bunch of libraries:

```bash
libboost_python.so
libcrypto.so.1.0.0
libcurl.so.4
libdf.so.0
libhdf5_hl.so.100
libhdf5.so.101
libjpeg.so.9
libmfhdf.so.0
libnetcdf.so.13
libOpenMM.so
libSireAnalysis.so.2018
libSireCAS.so.2018
libSireFF.so.2018
libSireIO.so.2018
libSireMM.so.2018
libSireMol.so.2018
libSireMove.so.2018
libSirePython.so.2018
libSireSystem.so.2018
libSireVol.so.2018
libSquire.so.2018
libssl.so.1.0.0
libtbbmalloc.so.2
libz.so.1
```

I'm running Linux (Arch) on multiple machines here and the tests work fine with the compiled and binary versions of 2018.1.1. Running `ldd` gives the same output for both `sire_test` binaries.

**Comment by jmichel80** [comment]
Hi,

I thought we were testing builds against ubuntu already as part of the pre-release process. 
I do think it is essential to support builds on this OS, at least a current LTS version. We can’t develop with Sire in the lab otherwise.

**Comment by chryswoods** [comment]
The illegal instruction (I guess) is because the processor is old and does not support AVX. The binary should work with Ubuntu on modern processors.

The test shows that the compilation did not work. We will pull out a Ubuntu 18.04 VM to try to debug why. At a first guess, I suspect that parts of the conda build process failed because they too now expect AVX to be supported. If they fail, the key libraries are not built and linked in correctly, hence the missing libraries and missing symbols.

Please confirm whether or not AVX is the issue by trying again on a computer with AVX support.

**Comment by jmichel80** [comment]
I have compiled sire from a fresh install of ubuntu 18.04. on my MBP 2017.
The compilation ended with this message

(...)
Something went wrong when trying to test the Sire installation.
libboost_python.so: cannot open shared object file: No such file or directory
Please check things manually yourself...


=================================
Congratulations. Everything has installed :-)

Importing modules fail 

julien@ubuntu:~/software/devel/BioSimSpace/python$ ~/sire.app/bin/python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Sire
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/julien/sire.app/lib/python3.5/site-packages/Sire/__init__.py", line 184, in <module>
    import Sire.Qt
  File "/home/julien/sire.app/lib/python3.5/site-packages/Sire/Qt/__init__.py", line 19, in <module>
    from Sire.Qt._Qt import *
ImportError: libSireStream.so.2018: cannot open shared object file: No such file or directory

I think there is an incompatibility with the python3 libraries  that come with that OS and the bundled version of boost_python. 

julien@ubuntu:~/sire.app/lib$ pwd
/home/julien/sire.app/lib
julien@ubuntu:~/sire.app/lib$ ldd libboost_python.so 
	linux-vdso.so.1 (0x00007ffcc2ffe000)
	libpython3.5m.so.1.0 => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd2cc5e4000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd2cc3cc000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd2cbfdb000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd2cbc3d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd2ccbb6000)

I tried to set wrapper to build against /usr/lib/x86_64-linux-gnu/libboost_python3.so but that failed.

What do you suggest to make the build work ?

**Comment by chryswoods** [comment]
Compilation should link only against the python library that comes with conda. It should not be using or seeing anything with the system. The wrapper should not be set to build against the libboost_python in /usr/lib, as Sire needs to build its own that is linked against the conda python.

Can you post the output of running "cmake ." in the wrapper directory. It is strange that cmake is finding and using the system python rather than the python with conda.

**Comment by chryswoods** [comment]
(I am setting up a ubuntu 18.04 image to see if it is a problem with ubuntu)

**Comment by chryswoods** [comment]
This is a problem with ubuntu. The compile_sire.sh script is correctly building sire, boost_python etc., but ubuntu is ignoring the ORIGIN path to find these libraries. Very strange, as it is correctly using it to find the Qt libraries etc.

The (hacky) workaround is to run Sire on Ubuntu 18.04 by passing the LD_LIBRARY_PATH manually on the command line, e.g.

LD_LIBRARY_PATH=$SIRE/lib $SIRE/bin/sire_test

works fine on vanilla 18.04 Ubuntu.

I lose my desktop with VMs all next week as the office is being refurbished, but will hunt down why this is broken once I am back from the Co-Lo visit. This completely does not make any sense...

**Comment by chryswoods** [comment]
Just to add, I've now compiled and successfully run the test on vanilla Ubuntu 16.04.4 LTS, 17.10.1 LTS and 18.04 LTS. The only packages that need installing are git, cmake and g++ (e.g. sudo apt install git cmake g++). The following commands now work;

`git clone https://github.com/michellab/Sire; cd Sire; ./compile_sire.sh; ~/sire.app/bin/sire_tests`

The only test failure is test_broken_amberprm.py, which is currently because it is a broken test (rather than broken code).

There are also failures on Ubuntu 16 because Sire fails to find and automatically compile in openmm support for Ubuntu 16. This is not a problem on Ubuntu 17 and Ubuntu 18.

As noted before, you need to compile and run Sire on modern (post 2011) processors that support AVX. Compilation will fail with weird errors if AVX is not supported, because many of the tools we rely on from conda are now AVX only.

**Comment by jmichel80** [comment]
git pull origin
and
./compile_sire.sh

gives me this output

[ 40%] Building CXX object src/libs/SireMol/CMakeFiles/SireMol.dir/molresid.cpp.o
[ 41%] Building CXX object src/libs/SireMol/CMakeFiles/SireMol.dir/molwithresid.cpp.o
[ 41%] Building CXX object src/libs/SireMol/CMakeFiles/SireMol.dir/molviewproperty.cpp.o
[ 41%] Building CXX object src/libs/SireMol/CMakeFiles/SireMol.dir/mover.cpp.o
[ 41%] Building CXX object src/libs/SireMol/CMakeFiles/SireMol.dir/parser.cpp.o
Build is in progress...
In file included from /usr/include/boost/variant/variant.hpp:43:0,
                 from /usr/include/boost/spirit/home/support/info.hpp:14,
                 from /usr/include/boost/spirit/home/qi/domain.hpp:16,
                 from /usr/include/boost/spirit/home/qi/meta_compiler.hpp:15,
                 from /usr/include/boost/spirit/home/qi/action/action.hpp:14,
                 from /usr/include/boost/spirit/home/qi/action.hpp:14,
                 from /usr/include/boost/spirit/home/qi.hpp:14,
                 from /usr/include/boost/spirit/include/qi.hpp:16,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMol/parser/ast.h:43,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMol/parser.cpp:30:
/usr/include/boost/math/common_factor_ct.hpp:22:26: error: ‘boost::integer::static_gcd_type’ has not been declared
    using boost::integer::static_gcd_type;
                          ^~~~~~~~~~~~~~~
src/libs/SireMol/CMakeFiles/SireMol.dir/build.make:1646: recipe for target 'src/libs/SireMol/CMakeFiles/SireMol.dir/parser.cpp.o' failed
make[2]: *** [src/libs/SireMol/CMakeFiles/SireMol.dir/parser.cpp.o] Error 1
CMakeFiles/Makefile2:1318: recipe for target 'src/libs/SireMol/CMakeFiles/SireMol.dir/all' failed
make[1]: *** [src/libs/SireMol/CMakeFiles/SireMol.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
SOMETHING WENT WRONG WHEN COMPILING CORELIB!

Will now try from a fresh git clone

**Comment by jmichel80** [comment]
Sadly :-(

git clone https://github.com/michellab/Sire; cd Sire; ./compile_sire.sh

(...)
[ 45%] Building CXX object src/libs/SireMol/CMakeFiles/SireMol.dir/mover.cpp.o
[ 45%] Building CXX object src/libs/SireMol/CMakeFiles/SireMol.dir/parser.cpp.o
In file included from /usr/include/boost/variant/variant.hpp:43:0,
                 from /usr/include/boost/spirit/home/support/info.hpp:14,
                 from /usr/include/boost/spirit/home/qi/domain.hpp:16,
                 from /usr/include/boost/spirit/home/qi/meta_compiler.hpp:15,
                 from /usr/include/boost/spirit/home/qi/action/action.hpp:14,
                 from /usr/include/boost/spirit/home/qi/action.hpp:14,
                 from /usr/include/boost/spirit/home/qi.hpp:14,
                 from /usr/include/boost/spirit/include/qi.hpp:16,
                 from /home/julien/software/devel/Sire/corelib/src/libs/SireMol/parser/ast.h:43,
                 from /home/julien/software/devel/Sire/corelib/src/libs/SireMol/parser.cpp:30:
/usr/include/boost/math/common_factor_ct.hpp:22:26: error: ‘boost::integer::static_gcd_type’ has not been declared
    using boost::integer::static_gcd_type;
                          ^~~~~~~~~~~~~~~
src/libs/SireMol/CMakeFiles/SireMol.dir/build.make:1646: recipe for target 'src/libs/SireMol/CMakeFiles/SireMol.dir/parser.cpp.o' failed
make[2]: *** [src/libs/SireMol/CMakeFiles/SireMol.dir/parser.cpp.o] Error 1
CMakeFiles/Makefile2:1218: recipe for target 'src/libs/SireMol/CMakeFiles/SireMol.dir/all' failed
make[1]: *** [src/libs/SireMol/CMakeFiles/SireMol.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
SOMETHING WENT WRONG WHEN COMPILING CORELIB!

**Comment by chryswoods** [comment]
Have you removed $HOME/sire.app before recompiling? The error looks like it is using the old boost headers in an old sire.app directory so not finding boost::spirit. The boost::spirit included is from /usr/include when it should be from sire.app/pkgs/sire-2018.X/bundled/include.

To recompile from scratch run

rm -rf $HOME/sire.app build/corelib build/wrapper
./compile_sire.sh

Let me know if this works.

**Comment by jmichel80** [comment]
Yes that helped. I now get an OpenMM linking error

[ 86%] Building CXX object src/libs/SireMove/CMakeFiles/SireMove.dir/volumemove.cpp.o
[ 86%] Building CXX object src/libs/SireMove/CMakeFiles/SireMove.dir/zmatmove.cpp.o
[ 86%] Building CXX object src/libs/SireMove/CMakeFiles/SireMove.dir/zmatrix.cpp.o
Build is in progress...
In file included from /home/julien/software/devel/Sire/corelib/src/libs/SireVol/coordgroup.h:34:0,
                 from /home/julien/software/devel/Sire/corelib/src/libs/SireMol/atomcoords.h:34,
                 from /home/julien/software/devel/Sire/corelib/src/libs/SireMove/zmatrix.h:35,
                 from /home/julien/software/devel/Sire/corelib/src/libs/SireMove/zmatrix.cpp:31:
/home/julien/software/devel/Sire/corelib/src/libs/SireMaths/vector.h: In member function ‘void SireMove::ZMatrixCoords::add(const SireMol::AtomID&, const Length&, const SireMol::AtomID&, const Angle&, const SireMol::AtomID&, const Angle&, const SireMol::AtomID&)’:
/home/julien/software/devel/Sire/corelib/src/libs/SireMaths/vector.h:274:27: warning: ‘<anonymous>.SireMaths::Vector::sc[3]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         sc[i] = other.sc[i];
                 ~~~~~~~~~~^
/home/julien/software/devel/Sire/corelib/src/libs/SireMaths/vector.h: In member function ‘void SireMove::ZMatrixCoords::add(const SireMove::ZMatrixCoordsLine&)’:
/home/julien/software/devel/Sire/corelib/src/libs/SireMaths/vector.h:274:27: warning: ‘<anonymous>.SireMaths::Vector::sc[3]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         sc[i] = other.sc[i];
                 ~~~~~~~~~~^
[ 86%] Building CXX object src/libs/SireMove/CMakeFiles/SireMove.dir/openmmmdintegrator.cpp.o
In file included from /home/julien/software/devel/Sire/corelib/src/libs/SireMove/openmmmdintegrator.cpp:31:0:
/home/julien/software/devel/Sire/corelib/src/libs/SireMove/openmmmdintegrator.h:35:10: fatal error: OpenMM.h: No such file or directory
 #include <OpenMM.h>   // CONDITIONAL_INCLUDE
          ^~~~~~~~~~
compilation terminated.
src/libs/SireMove/CMakeFiles/SireMove.dir/build.make:1334: recipe for target 'src/libs/SireMove/CMakeFiles/SireMove.dir/openmmmdintegrator.cpp.o' failed
make[2]: *** [src/libs/SireMove/CMakeFiles/SireMove.dir/openmmmdintegrator.cpp.o] Error 1
CMakeFiles/Makefile2:1285: recipe for target 'src/libs/SireMove/CMakeFiles/SireMove.dir/all' failed
make[1]: *** [src/libs/SireMove/CMakeFiles/SireMove.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
SOMETHING WENT WRONG WHEN COMPILING CORELIB!

This is because openmm was not correctly installed it seems

  Could not detect the OpenMM plugin directory at the default location
  (/home/julien/sire.app/lib/plugins).Check your OpenMM installation or set
  the OPENMM_PLUGIN_DIR environment variable!
Call Stack (most recent call first):
  CMakeLists.txt:806 (FIND_PACKAGE)
-- Found OpenMM at /home/julien/sire.app

Scrolling up, it looks like something odd happened with conda 

Executing transaction: done
Installing openmm from the omnia repository...
Warning: 'http://conda.binstar.org/omnia' already in 'channels' list, moving to the top
Solving environment: done

## Package Plan ##

  environment location: /home/julien/sire.app

  added / updated specs: 
    - openmm=7.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openmm-7.0.1               |           py35_0        11.5 MB  http://conda.binstar.org/omnia
    fftw3f-3.3.4               |                2         1.2 MB  http://conda.binstar.org/omnia
    ------------------------------------------------------------
                                           Total:        12.7 MB

The following NEW packages will be INSTALLED:

    fftw3f: 3.3.4-2      http://conda.binstar.org/omnia
    openmm: 7.0.1-py35_0 http://conda.binstar.org/omnia


Downloading and Extracting Packages
openmm-7.0.1         | 11.5 MB | #############################################################################################################5                                     |  75% 
fftw3f-3.3.4         |  1.2 MB | #############################################################################################################5                                     |  75% 

ValueError('n (-1.0550582346557924e-05) cannot be negative',)
ValueError('n (-9.984056831602306e-05) cannot be negative',)

I don't recall seeing this error before....

**Comment by jmichel80** [comment]
So what I did in the end is to manually install openmm 7 after the first build attempt failed

~/sire.app/bin/conda install openmm=7.0

and then run compile-sire.sh again. 

this worked, ~/sire.app/bin/sire_test is now running :-)

**Comment by chryswoods** [comment]
That is very strange. The compile and install worked without your extra openmm step on the Ubuntu 18 test VM... Also, if cmake detects that OpenMM is not available then it disables the OpenMM code, so you shouldn't see errors relating to missing openmm header files. Very strange. Pleased it now (mostly) works ;-)

**Comment by chryswoods** [comment]
Closing as builds should now be made from docker, and also made build system more robust
