### ISSUE TITLE
GROMACS parser unable to read system when molecule has non-alphanumeric name

### ISSUE THREAD

**Issue by lohedges** [michellab/Sire#250]
Sire cannot read the following Gromacs files:

```python
from Sire.IO import MoleculeParser

s = MoleculeParser.read(["files/test.gro", "files/test.top"])
```

This gives the following error:

```bash
...
_EndTrace__
Exception 'SireIO::parse_error' thrown by the thread 'master'.
Could not construct a molecule system from the information stored in this Gromacs topology file. Errors include:
Error constructing the molecule associated with template '*****' : There is no molecular template called '*****' in this Gromacs file. Available templates are [ [ , SOL ] ]
Thrown from FILE: /home/lester/Code/Sire/corelib/src/libs/SireIO/grotop.cpp, LINE: 7041, FUNCTION: virtual SireSystem::System SireIO::GroTop::startSystem(const SireBase::PropertyMap&) const
```

The topology file was created by solvating a molecule originally loaded from a (supposedly) legitimate Mol2 file. In this file, the molecule is named `*****`. Sire fails to find the `[ moleculetype `] section where `*****` is defined. Renaming it to any sensible name, e.g. `MOL`, in both the `[ moleculetype ]` and `[ molecules ]` sections fixes the problem.

[files.tar.gz](https://github.com/michellab/Sire/files/2911288/files.tar.gz)

**Comment by chryswoods** [comment]
Any line that starts with a “*” is a comment line according to the gromacs topology file specification. This is caught in the preprocess function in SireIO/grotop.cpp. This meant that the name of the template was not set, hence the null name. The correct behaviour should have been to raise an exception if the molecule template name was not set.

This does raise the interesting point about how we deal with atom, residue, molecule names that are valid characters in one file specification, but not in another (e.g. includes a comment character or Unicode character or emoji that is unsupported - Sire internally uses Unicode for all strings so should work with atoms labelled with emojis...)

As a test, see what happens if you use only emojis for names in a (silly) mol2 file and see what happens when it converted to grotop ;-)

**Comment by lohedges** [comment]
Ah, interesting. I hadn't realised that the `*` character is a comment in GROMACS. As you say, perhaps we need to keep track of the invalid naming conventions for different file formats so that we can catch and convert where necessary. As always though, we don't want to be too clever and end up doing things behind the user's back that they aren't aware of.
