### ISSUE TITLE
Question regarding analyse_freenrg.py and simfile.dat

### ISSUE THREAD

**Issue by maxkuhn** [michellab/Sire#279]
I am trying to evaluate the impact of the number of lambda windows on the free energy. However, I do not wish to calculate the same perturbation multiple times using a different number of windows (e.g. running the perturbation with a lambda step size of 0.2 and then running it again with a step size of 0.1).

Instead, I would like to

1. set up a perturbation with a step size of 0.1 **but only run the calculations for lambda = 0.0, 0.2, 0.4, 0.6, 0.8 and 1.0**
2. run analyse_freenrg.py on the windows calculated so far
3. run the remaining simulations at lambda = 0.1, 0.3, 0.5, 0.7 and 0.9
4. run analyse_freenrg.py on all windows

To tackle this, I wrote a script which cuts out the columns for the not yet calculated lambda values in `simfile.dat` after step 1. When I run `analyse_freenrg.py` on this modified files, I do get reasonable values for TI. However, the energies obtained by MBAR are odd, as is the overlap matrix, in which the columns and rows no longer add up to 1. 

It seems that I have not fully understood how the energies via MBAR and the overlap matrix are calculated from the SOMD output files. I would be very happy if someone could elaborate on this a little bit. I would also like to have feedback whether the approach described above is reasonable or whether there are further obstacles I have not considered. I am also wondering whether modifying `simfile.dat` is enough or whether I also need to implement some changes to other files.

**Comment by ppxasjsm** [comment]
MBAR and TI are very different estimators. MBAR is a reweighting estimator and will need bias information form every lambda window calculated at every lambda window. 
I assume you evaluate the biases at the dense lambda schedule even for the simulations that have not been run yet. 

Cutting out columns for `analyse_freenrg.py` should work if you also only supply the truncated set of lambda windows and not the full set and you remove essentially all the u_kln that do not exist yet with data. 

The only thing I can think of is that there is a mismatch between supplied lambdas and calculated lambdas, but it is ok, because the biases are all calculated. Currently, with Sire, there is no easy way of postprocessing bias energies for different lambda windows if they have not been predefined. 

If you could give me an example of your adjusted file and how you call analyse_freenrg then I might be able to give you more specific information.

**Comment by maxkuhn** [comment]
ppxasjsm was able to solve this yesterday. I was using '--percent 95' when running mbar. However, there was not enough overlap between the remaining windows which caused MBAR  to give unreasonable results. After checking this (when running analyse_freenrg) reasonable numbers are obtained.
