### ISSUE TITLE
optimise_openmm does not work in conda environment

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#283]
Trying to run optimise_openmm when biosimspace is installed in a conda envrionment the following error occurs:

```bash
Starting optimise_openmm: number of threads equals 20
CUDA platform is not recognised by OpenMM!
available platforms are: 
['Reference', 'CPU', 'OpenCL']
Let's see if we can do something about this....

Cannot find a 'conda' binary in directory '/home/ppxasjsm/miniconda3/envs/ucb/bin'. Are you running this script using the python executable from a valid miniconda or anaconda installation within Sire?
```

**Comment by lohedges** [comment]
The problem is that the `conda` executable doesn't exist within a Conda environment. It is used to configure and manage the environment, but lives outside of it. For the Sire application, it is actually bundled in one place.

You probably just want to search for Conda using `Sire.Base.findExe` (if your existing check fails). You should also check that you can import Sire at the top of the script to make sure that Sire is installed into the Conda environment, e.g.:

```python
try:
    import Sire
except:
    # raise some exception
```

**Comment by ppxasjsm** [comment]
yep already on it.

**Comment by ppxasjsm** [comment]
befbefc1 fixes this.

**Comment by ppxasjsm** [comment]
Is the try import sire necessary? optimising openmm is part of Sire.

**Comment by lohedges** [comment]
Sorry, my idea was wrong. This now won't work for a regular Sire installation, since it won't find the correct Conda. You'll need to use `Sire.Base.getBinDir` instead, which gives the correct `bin` path both for a regular Sire installation and the Conda package.

**Comment by ppxasjsm** [comment]
I have an easy fix.

**Comment by lohedges** [comment]
Easier than:

```
conda_base = Sire.Base.getBinDir()
```

**Comment by ppxasjsm** [comment]
Nope:
`
Sire.Base.getBinDir()                                                                                                          
Out[2]: '/home/ppxasjsm/miniconda3/envs/ucb/bin'
`
