### ISSUE TITLE
Change the frequency somd-freenrg restart files are written

### ISSUE THREAD

**Issue by nigel-cresset** [michellab/Sire#290]
Hi, is there a way to change the frequency which somd-freenrg writes restart files? It would be useful to limit somd-freenrg to only write restart files every X cycles to reduce the amount of time spend in disk I/O.

**Comment by lohedges** [comment]
We currently write a rst/prm file every cycle because of [this](https://github.com/michellab/Sire/issues/281) unresolved issue. This is needed to allow updated atomic coordinates to be read back into the original molecular system by BioSimSpace. I can certainly add an option to change the frequency of write, although I believe most other IO is performed on a per cycle basis regardless, e.g. the simfile.

**Comment by lohedges** [comment]
Ah, perhaps you did mean the binary S3 restart file. I'll check tomorrow. Should be easy to add an option if required.

**Comment by jmichel80** [comment]
This could be done with a config keyword. Be careful about keeping the restart and simfile in sync with the simulation time step otherwise it will be messy to restart jobs and get consistent output for free energy estimation.

**Comment by nigel-cresset** [comment]
Yes, I was thinking of the binary S3 restart file. I was hoping for something like waterswap "restart frequency" setting.

**Comment by lohedges** [comment]
@jmichel80: This is the section of [OpenMMMD.py](https://github.com/michellab/Sire/blob/devel/wrapper/Tools/OpenMMMD.py) where data is written to the `simfile.dat` and `restart.s3` files:

```python
for i in range(cycle_start, cycle_end):
        print("\nCycle = ", i, "\n")
        system = moves.move(system, nmoves.val, True)
        if save_coords.val:
            writeSystemData(system, moves, trajectory, i, softcore_lambda)

        mdmoves = moves.moves()[0]
        integrator = mdmoves.integrator()

        #saving all data
        beg = (nmoves.val*(i-1))
        end = nmoves.val*(i-1)+nmoves.val
        steps = list(range(beg, end, energy_frequency.val))
        outdata = getAllData(integrator, steps)
        gradients = integrator.getGradients()
        fmt =" ".join(["%8d"] + ["%25.8e"] + ["%25.8e"] + ["%25.8e"] + ["%25.8e"] + ["%25.15e"]*(len(lambda_array.val)))
        np.savetxt(outfile, outdata, fmt=fmt)

        mean_gradient = np.average(gradients)
        outgradients.write("%5d %20.10f\n" % (i, mean_gradient))
        for gradient in gradients:
            #grads[lambda_val.val].accumulate(gradients[i-1])
            grads[lambda_val.val].accumulate(gradient)
        # Save restart
        print("Backing up previous restart")
        cmd = "cp %s %s.previous" % (restart_file.val, restart_file.val)
        os.system(cmd)
        print ("Saving new restart")
        Sire.Stream.save([system, moves], restart_file.val)
```

Is it safe to put the part following `# Save restart` inside a conditional block so that we only stream to file every `n` cycles? This would leave the write frequency of the `simfile.dat` unaffected. (Or do they need to be written at the same frequency.)

I also note that trajectory data (and my prm/rst modifications) are written separately in the `writeSystemData` function. This would also be unaffected by this change.

**Comment by jmichel80** [comment]
Is it safe to put the part following # Save restart inside a conditional block so that we only stream to file every n cycles? This would leave the write frequency of the simfile.dat unaffected. (Or do they need to be written at the same frequency.)

No simfile.dat and restart_file.val should be saved with the same frequency. Consider the scenario where simfile.dat is saved every cycle but sim_restart.val is saved every three cycle.
After cycle 8 the job crashes. The data in simfile.dat includes cycles 1 to 7 but the last sim_restart.val file is for cycle 6. When the simulation is resumed it will proceed by repeating the sampling done during cycle 6 to 7 and this will add artefactual correlations to the energies saved in simfile.dat.

Be careful with the the lines of code

#saving all data
beg = (nmoves.val*(i-1))
end = nmoves.val*(i-1)+nmoves.val
steps = list(range(beg, end, energy_frequency.val))
outdata = getAllData(integrator, steps)

the logic to work out the beginning and end of the section of energies to collect needs to be changed to deal with multiple cycles.


I also note that trajectory data (and my prm/rst modifications) are written separately in the writeSystemData function. This would also be unaffected by this change.

This should also be synchronized with the saving of simfile.dat and sim_restart.val to avoid introducing problems when restarting jobs.

BW

Julien
The University of Edinburgh is a charitable body, registered in Scotland, with registration number SC005336.

**Comment by lohedges** [comment]
Thanks, I'll take a look when I have some time.

For now, would it not work to simply reduce the number of cycles and increase the number of moves per cycle?

**Comment by jmichel80** [comment]
For now, would it not work to simply reduce the number of cycles and increase the number of moves per cycle?


Yes that should work actually!

Julien

**Comment by nigel-cresset** [comment]
Ok, I will reduce the number of cycles and increase the number of moves and see what effect that has. Many thanks for your help.
