### ISSUE TITLE
Assertion failure in analyse_freenrg.py

### ISSUE THREAD

**Issue by mark-cresset** [michellab/Sire#293]
Running 

`
/home/mark/gui/trunk/buildDependencies/sire/linux-x86_64/bin/sire_python /home/mark/gui/trunk/buildDependencies/sire/linux-x86_64/share/Sire/scripts/analyse_freenrg.py mbar -i /tmp/analyse_freenrg_mbar_30125_3/simfile_{0,1,2,3,4}.dat -o /tmp/analyse_freenrg_mbar_27262_1/freenrg-MBAR2.dat --temperature 298.0 --percent 95 --overlap
`
seems to be nondeterministic, and occasionally asserts. The line in the output:

```
Final dimensionless free energies
f_k = 
[  0.          92.67254303  99.5993755   35.29315774 -26.93507728]

```
has different numbers every time, and occasionally I get an assert from check_w_normalized:

pymbar.utils.ParameterError: Warning: Should have \sum_n W_nk = 1.  Actual column sum for state 0 was 0.999897. 4 other columns have similar problems.

The 0.999897 number varies.
[analyse_freenrg_bug.zip](https://github.com/michellab/Sire/files/3580093/analyse_freenrg_bug.zip)

**Comment by lohedges** [comment]
Hi Mark,

I'm sure @ppxasjsm will be able to provide more details, but I'm not sure that the results will be reproducible unless your data is converged. (Because of the way MBAR samples and bootstraps.)

It looks like you don't have very good data with no overlap between lambda windows. Here is the overlap matrix from the output `dat` file:

```sh
#Overlap matrix
1.0000 0.0000 0.0000 0.0000 0.0000
0.0000 1.0000 0.0000 0.0000 0.0000
0.0000 0.0000 0.9997 0.0003 0.0000
0.0000 0.0000 0.0003 0.9997 0.0000
0.0000 0.0000 0.0000 0.0000 1.0000
```

All off-diagonal entries are zero, i.e. there is no overlap between any given lambda window and the adjacent ones. The code also gives the following `UserWarning` to highlight this:

```sh
UserWarning: Off diagonal elements of the overlap matrix are smaller than 0.03! Your free energy estimate is not reliable!
```

I'd suggest increasing the number of windows and running again.

**Comment by mark-cresset** [comment]
OK, this has happened often in testing, but for speed during QA we often do short runs with few lambda windows which are probably not fully converged. If this is unlikely to happen for converged runs then it's much less of an issue for us.

**Comment by ppxasjsm** [comment]
Sorry for the slow reply. I was on holiday until today. I think Lester already pointed out the essential thing. I'll look into maybe changing the test then if it fails too often its annoying and clearly not a good test.
