### ISSUE TITLE
Waterswap fails at around 1500-1600 steps possibly due to freenrg_components.s3 being too large

### ISSUE THREAD

**Issue by sas103** [michellab/Sire#310]
Hello,

I am very sorry to have to raise another issue so close to the previous one, but I have encountered another problem, this time with WaterSwap.

Summary:

1. An initial WaterSwap calculation was run without problems up to 1000 steps, using identical input files to the ones provided.
2. Due to poor convergence, I decided to extend the calculation (by restarting it, and simply changing nmoves = 1000 to nmoves = 5000 in the configuration files).
3. At around 1500-1600 moves, the calculation fails, and freenrg_components.s3 is opened but not written. By this point, freenrg_components.s3.bak is ~300 MB in size, so I suspect it may be due to memory / file handling issues.
4. Copying all .s3.bak files to .s3 and restarting repeats the previous 20 steps, but the calculation invariably fails again once the new freenrg_components.s3 must be written.
5. Starting from scratch (0 to 5000 steps directly) does not solve the situation. I am attaching STDOUT.out (which goes up to 1413 only, even though the actual calculation crashed at 1570 moves), as well as STERR.err; the slurm script; the topology and coordinates; and the configuration files. freenrg_components.s3.bak, for reference, is 287.9 MB in size.

Question: is the issue really due to the size of freenrg_components.s3, and if so, is there some way I could break any s3 files into smaller chunks?

Many thanks in advance for your help, and best regards,

Stefano
[slurm_STDERR_STDOUT_input.zip](https://github.com/michellab/Sire/files/4277089/slurm_STDERR_STDOUT_input.zip)

**Comment by chryswoods** [comment]
Yes, you are right that this is a crash caused by too much memory being used. The freenrg_components.s3 file causes a lot of problems once the number of iterations goes above 1000, as it contains all of the energy components between lots of molecules over lots of iterations. The file itself is written by streaming the data into memory, and then in-memory compressing and writing to disk. Compression is quite good, so a 287 MB file is likely to have ~3 GB+ of data. This would be on top of the memory used by the ~16 replicas of the system.

The solution is to reduce the frequency of writing out the freenrg_components.s3 file. It is not really needed as it is only used when you restart a waterswap calculation (I have often thought about removing it completely!). To do this, you should increase the number of steps per iteration, rather than increasing the number of iterations. You can also reduce the frequency of writing the restart files. Do this by setting the values in your config to,

```
restart frequency = 100
nsubmoves = 100000
```

(I have x10 reduced the frequency of writing restart files, and doubled the number of MC moves per iteration).

Hopefully now you will reach 1000 iterations and will converge the free energy without having a crash caused by the freenrg_components.s3 file.

However, in my experience, waterswap will either converge in 1000 iterations or it won't. Adding more iterations doesn't really help, and continuing/restarting the simulation didn't ever work for me. Poor convergence also hints at quite a large random error, meaning that if you run the same calculation 4 times, then you may get 4 very different results. Poor convergence is normally because waterswap performs badly for some shapes of ligand, e.g. long and thin, or spindly. It works best for small ligands (or fragments).

**Comment by sas103** [comment]
Many thanks for taking a look at this. I will bear in mind what you said about possible issues with long / spindly ligands; and indeed, my ligand (ATP) is relatively long and convoluted. Let's say that the convergence is not abysmal: 4 different runs with four different representative snapshots give values that range from -190 to -220 kcal mol-1. Two of the three methods used to calculate the free energy are in quite good agreement, the third is about -20 kcal mol-1 off.

At any rate, I will rerun the calculation with your suggested modifications right away, and let you know once that finishes.

**Comment by sas103** [comment]
Hi Chris,

I ran the simulations with the increased number of submoves, and I can confirm what you said about poor convergence (see four outputs pasted below with analyse_freenrg over 60%). Bennetts' free energy remains consistently higher than the other two methods in all four cases. In fact, although they should be similar but not identical, as they have different starting points, calculated values still differ - as you predicted - from the original set of simulations that I ran. As such, I will consider waterswap not to be useful for my kind of ligand, and will close the issue. Thanks very much for your help and advice!!!!!!

Stefano

==> atA_pt1/output/results.txt <==
 Bennetts = 212.43077025685275 +/- 0.2136662662887766 kcal mol-1
 FEP = 194.6576475048321 +/- 57.284855112984694 kcal mol-1
 TI = 195.47100346315392 +/- 4.774557742948048 kcal mol-1 (quadrature = 199.27348141928027 kcal mol-1)


==> atA_pt2/output/results.txt <==
 Bennetts = 194.21352637698473 +/- 0.19079138126725131 kcal mol-1
 FEP = 176.12180821754373 +/- 70.74433995785947 kcal mol-1
 TI = 180.26189407001917 +/- 4.52428787403548 kcal mol-1 (quadrature = 181.16715425199703 kcal mol-1)

==> atB_pt1/output/results.txt <==
Bennetts = 226.95579595338248 +/- 0.22531521378182418 kcal mol-1
FEP = 211.44806874203533 +/- 51.335962716931476 kcal mol-1
TI = 207.35429911659102 +/- 4.044059414154788 kcal mol-1 (quadrature = 212.17043969651724 kcal mol-1)

==> atB_pt2/output/results.txt <==
Bennetts = 216.15317449374942 +/- 0.23025853482514655 kcal mol-1
FEP = 203.80887172270877 +/- 48.221237282833464 kcal mol-1
TI = 203.78183505638455 +/- 5.1859759029270265 kcal mol-1 (quadrature = 208.83337076938915 kcal mol-1)
