### ISSUE TITLE
Pair Generation Issue in 2019.3.0

### ISSUE THREAD

**Issue by miroslav351** [michellab/Sire#312]
Hi,

I have been having issues with topology files generated by BioSimSpace/Sire 2019.3.0 (simulations crashing) that I didn't observe with BioSimSpace/Sire 2019.2.0. After some testing, I found that the [ pairs ] directive is not generated in the new version, which means that GROMACS doesn't scale 1,4 interactions by the fudge factors and the simulations crash.

I am not completely sure whether it's BioSimSpace or Sire but my best guess is that it's Sire 2019.3, and the bug is related to the recent overhaul of the GroTop parser to make it more efficient.

I have attached a cyclohexane in vacuum test case with initial files generated with AMBER/ParmEd and then the two topology files generated by BioSimSpace/Sire 2019.2.0 and BioSimSpace/Sire 2019.3.0 and their differences: 
[files.zip](https://github.com/michellab/BioSimSpace/files/4337850/files.zip)

Many thanks.

**Comment by lohedges** [comment]
I can confirm that the issue occurs after [this](https://github.com/michellab/Sire/commit/45c26630de52e3cd71fb05e837be7a4cd3ad1502) commit, i.e. looping over the intrascale matrix by cutgroups rather than atoms to avoid the N^2 loop. I tested this before pushing, so I'm not sure what I've missed.

Will try to debug as soon as possible.

**Comment by lohedges** [comment]
Okay, I've figured out the issue and it should be an easy fix. Should hopefully be able to sort this later today.

Thanks again for posting.

**Comment by miroslav351** [comment]
Thank you for the quick reply! I will stay tuned.

**Comment by lohedges** [comment]
This should now be fixed. It'll take an hour or so before an updated binary and conda package is available. Let me know if you run into any similar issues with the pairs list for any topology files for FEP simulations. I tested here and it looked okay.

**Comment by chryswoods** [comment]
Thanks for both for raising the issue and for the quick turnaround :-)

**Comment by lohedges** [comment]
No problem. It looks like the Conda package build stage failed, probably because of some links still pointing to the chryswoods tenancy. I'll take a look at fixing this later.

**Comment by lohedges** [comment]
I think I've sorted out the download links for the compressed Sire library files that are used to create the Conda packages. (The PAR URLs in the Conda recipe template needed updating following the migration.) I've also updated the Anaconda cloud authorisation token since it was about to expire.

Hopefully I wake up to find that everything worked as expected 🤞

**Comment by chryswoods** [comment]
Excellent - it looks like it worked :-)
