### ISSUE TITLE
somd-freenry Error: Formal parameter space overflowed

### ISSUE THREAD

**Issue by rongfengzou** [michellab/Sire#314]
I'm trying to run TI with somd-freenry.

It works fine with CPU version, but get the following error with CUDA version.
RuntimeError: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x564b7039a010_85638.cu(651): Error: Formal parameter space overflowed (5372 bytes required, max 4096 bytes allowed) in function computeBondedForces.

I tested the case in the tutorial (lysosome system), both CPU and CUDA worked fine.

Could you please tell me how to solve this issue?
Best Regards,

**Comment by lohedges** [comment]
Hi there,

This is because you've hit the limit of the memory buffers that are used to
transfer perturbation parameters to the GPU. This can happen if you don't
have much GPU memory, or have a particularly large perturbation with lots
of terms.

Could you try running a smaller system on the GPU, e.g. ethane-methanol,
and confirm that it works.

Cheers.

**Comment by lohedges** [comment]
Just re-read your message. As you say, the tutorial works fine on both the
CPU and GPU because the perturbation is small enough to fit in memory on
the GPU.

**Comment by lohedges** [comment]
Closing as no update and this isn't a Sire/SOMD issue. (Although perhaps SOMD could present OpenMM errors in a more informative way.)
