### ISSUE TITLE
Switching to conda-forge OpenMM

### ISSUE THREAD

**Issue by lohedges** [michellab/Sire#334]
OpenMM is now available through [https://anaconda.org/conda-forge/openmm](conda-forge). I was hoping to remove the `omnia` channel dependency but there appear to be a couple of issues:

* The `conda-forge` package pulls in the [cudatoolkit](https://anaconda.org/anaconda/cudatoolkit) package as a dependency. This is almost a GB in size and would massively bloat our binary if we needed to bundle it too. (Even if we don't bundle it for the binary, it would be an unavoidable download for our conda package.)
* Unlike the [omnia](https://anaconda.org/omnia/openmm) version, there are no labels for specific versions of the Cuda driver, hence our [optimise_openmm.py](https://github.com/michellab/Sire/blob/devel/wrapper/python/scripts/optimise_openmm.py) script will no longer work. This is useful when the user wants to install a different version of OpenMM when running on a different system, e.g. HPC. (Perhaps we could leave this script as is and use the `omnia` channel for specific version pulls.)
* The `omnia` version only has support up to Python 3.7, so if we want to upgrade to 3.8/3.9 (which would be a good thing long term), then we'll need to switch to `conda-forge`.

**Comment by chryswoods** [comment]
That is really annoying. I think you may need to raise an issue with OpenMM asking why they have bundled cudatoolkit. An extra 1 GB download is a lot. If they have a good reason then we are stuck with that as this would become the main and supported version. There aren't any good solutions - if we bundle then our installer is too large. If we don't bundle and install later, then we open up to a whole range of support issues if there an incompatibilities introduced by re-running conda install.

You should also ask about the lack of labels. optimise_openmm was needed because OpenMM didn't work optimally on all computers. If they have solved this problem then we wouldn't need optimise_openmm. I'd be reticent to push people to the omnia channel if we've jumped to conda-forge as this will cause support headaches in the future, especially as we see higher adoption of python 3.8 and 3.9.

**Comment by lohedges** [comment]
Yes, it's a pain, but seems to be the conda way. It would be nice if they had another version of the package which didn't bundle the CUDA ToolKit, since you don't require it to use OpenMM unless you want to run on a GPU, and then you might have a pretty custom setup. 

With regards to the labels: Perhaps there's no need for the them anymore, i.e. you might be able to specify a version of the toolkit which would automatically pin the required version of OpenMM, e.g.

```
conda install -c conda-forge openmm cudatoolkit=10
```

**Comment by lohedges** [comment]
Closing since we now build on top of conda-forge OpenMM.
