### ISSUE TITLE
ttb/atomic.h deprecated

### ISSUE THREAD

**Issue by lohedges** [michellab/Sire#340]
While building Sire, we are now seeing the following compiler warnings:

```
 #pragma message("TBB Warning: tbb/atomic.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual."
```

It looks like the [atomic template class](https://www.threadingbuildingblocks.org/docs/help/reference/appendices/deprecated_features/cpp_obsolete/atomic_cls.html) is now deprecated, although it's not clear when it will be removed. This is used by [SireBase/refcoundata.h])(https://github.com/michellab/Sire/blob/devel/corelib/src/libs/SireBase/refcountdata.h), so we should think of an alternative.

**Comment by chryswoods** [comment]
Oh... that's a pain as RefCountData is a foundational class. It provides the reference counter for all of our copy-on-write shared data classes. I believe I switched to the TBB atomic because access to the atomic integer in QSharedData (https://doc.qt.io/qt-5/qshareddata.html) became difficult (breaking ABI or access became private). The nice thing about TBB is that it is a (mostly) header only library, so we could abstract this out. Or, it may be that this is deprecated because atomics are now part of C++ (based on a quick search - https://en.cppreference.com/w/cpp/atomic/atomic). 

Indeed, thinking while I type, it is very likely that this is deprecated because of std::atomic. Looking at the API, it should be very easy to replace tbb::atomic<int> with std::atomic<int> (the header is <atomic>). 

The `fetch_and_increment()` tbb function looks like it can be replaced by `fetch_add(1)`, while `fetch_and_decrement()` can be replaced by `fetch_sub(1)`. They both give the same semantics, i.e. atomic increment/decrement by one while returning the previous value.

`load()` is the same, and `fetch_and_store(0)` can be replaced by `exchange(0)`.

We could also remove the tbb::spin_mutex and the `#ifdef SIRE_USE_REFCOUNT_MUTEX` as the fallback to a mutex if the processor doesn't support atomic operations is now handled by std::atomic automatically (e.g. see `is_always_lock_free`, which implies to me that if atomic operations aren't supported, then they will fall back to using a lock).

**Comment by lohedges** [comment]
Thanks, this is really helpful. I'll try to make the switch to `std::atomic` this morning and see how it goes. I _assume_ that there are things in SireUnitTests that would break if this doesn't work, or do we need to be more careful?

**Comment by chryswoods** [comment]
Yes, it is very foundational. If you get it wrong then lots of tests will segfault. This is explicitly tested in `SireUnitTests/unittests/SireBase/test_refcount.py`, and `SireUnitTests/unittests/SireStream/test_sharedstream.py`.

The only things that can go wrong are that you decrement the reference count incorrectly (meaning that the reference count never goes to zero, and so Sire leaks memory like anything - which will kill your machine, or that you decrement too much and delete objects prematurely and get use-after-free errors). Or that you increment the reference count incorrectly, in which case you will also see similar errors.

You could also test it by switching [Incremint](https://github.com/michellab/Sire/blob/devel/corelib/src/libs/SireBase/incremint.h) over from using a `QAtomicInt` to using a `std::atomic<int>`. You could write a very simple unit test that increments the `Incremint` 10 times and checks that the value is 10. (`Incremint` is the class that provides version numbers for all objects - these atomically increment whenever any Sire object is changed)

**Comment by lohedges** [comment]
I've made the suggested changes and both tests that you link to pass. I'll just run the whole test suite for piece of mind, then push the update.

I'm glad this was an easy fix. Thanks for your help!
