### ISSUE TITLE
compile sire results in issue with miniconda

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#349]
Not really sure what to make of this:

```
(base) ~/Projects_git/Sire$ ./compile_sire.sh 
Where would you like to install Sire? [/Users/toni_brain/sire.app]: 
Installing into directory '/Users/toni_brain/sire.app'
64 bit processor
x86_64 operating system
** Downloading miniconda from https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.3-MacOSX-x86_64.sh... **
** wget https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.3-MacOSX-x86_64.sh -O build/miniconda.sh 2>/dev/null || curl https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.3-MacOSX-x86_64.sh -o build/miniconda.sh  **
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
** Unpacking miniconda into /Users/toni_brain/sire.app... **
** bash build/miniconda.sh -b -p /Users/toni_brain/sire.app **
** FATAL **
** Cannot find conda python **
** Something went wrong with the miniconda install! **
** Remove /Users/toni_brain/sire.app, then run compile_sire.sh --clean, then try again **

```

**Comment by lohedges** [comment]
It looks like the miniconda hasn't downloaded (nothing transferred) so perhaps there was a network issue? I've checked the link here and it is still valid.

It also looks like you are building Sire within an existing conda environment (base) which could cause problems. Could you try building outside of conda.

I'll try a macOS build myself later this morning.

**Comment by lohedges** [comment]
I've tested here and it appears to be an issue with the curl command, which is what is used by default on macOS (since wget doesn't come installed as standard). The MiniConda download link has changed to being a redirect, which curl doesn't follow by default. Adding a `-L` flag to the command makes things work.

I'll update devel now and you can merge across into your feature branch. Just to note. If you add Doxygen style comments to your function (eitther the prototype or definition) then it will be picked up by the wrapper generator and added to the Python docstring. It might be worth calling the function something like `getSerialisedOpemMMSystem` just to be clear that what is returned is an OpenMM system, not a Sire one. (Not that I expect anyone to directly use this functionality.)
