### ISSUE TITLE
The requested CUDA device could not be loaded

### ISSUE THREAD

**Issue by kexul** [michellab/Sire#357]
Dear Sire developers: 
      Recently I encountered the following error frequently in my cluster. 
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/biosimspace/share/Sire/scripts/somd-freenrg.py", line 146, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/root/miniconda3/envs/biosimspace/lib/python3.7/site-packages/Sire/Tools/__init__.py", line 176, in inner
    retval = func()
  File "/root/miniconda3/envs/biosimspace/lib/python3.7/site-packages/Sire/Tools/OpenMMMD.py", line 1659, in runFreeNrg
    system = integrator.minimiseEnergy(system, minimise_tol.val, minimise_max_iter.val)
RuntimeError: The requested CUDA device could not be loaded
```

The simulation was performed by: `somd-freenrg -C somd.cfg -t somd.prm7 -c somd.rst7 -m somd.pert -p CUDA`, one lambda per GPU,  in nodes with spec: 
```
CPU:  192  AMD EPYC 7K62 48-Core Processor

GPU: NVIDIA A100-SXM4-40GB * 8 

CUDA runtime: 11.2.152

openMM version: 7.4.2,  build py37_cuda101_rc_1 from omnia
```
It's weird that only one GPU would fail in my 8 GPUs node. 

I googled a while and found this https://github.com/openmm/openmm/issues/1728 might help, but I don't know where I should put the parameter `'DisablePmeStream':'true'`, do you have any suggestions? Thanks!

**Comment by lohedges** [comment]
Hi there,

Could you let us know how the `CUDA_VISIBLE_DEVICES` environment variable is set for your node? For simplicity, SOMD assumes that you have _exclusive_ access to the node and defaults to a device index of 0 (which is actually an index into the `CUDA_VISIBLE_DEVICES_ARRAY`). This is worked well for us on various clusters where the scheduler makes sure to set `CUDA_VISIBLE_DEVICES` for you. Sometimes it can mask the values so you only ever need to use index 0, i.e. you have a single device visible to each GPU job on the node and it takes care of mapping to the correct GPU index.

It's possible that you aren't running with exclusive access, so someone else might have nabbed one of the free GPUs before your job started. Alternatively, the indexing could be wrong so you might need to manually set `gpu = X` in the SOMD configuration file for each GPU job on the node. (Probably 0 through 7, depending on what `CUDA_VISIBLE_DEVICES` reports when nothing is running.) We've not yet automated things for multi-GPU nodes, since the set-up is rather specific to the scheduler and cluster in question.

Unfortunately the `'DisablePmeStream':'true'` option would need to be set in Sire's C++ layer, since that part of the OpenMM interface hasn't been exposed to Python.

**Comment by kexul** [comment]
Hi @lohedges , Thanks for the quick reply, appreciated it!

> Could you let us know how the CUDA_VISIBLE_DEVICES environment variable is set for your node? 

I did not explicitly set `CUDA_VISIBLE_DEVICES` in my node and used `gpu=X` in SOMD configuration file to control which GPU to use. 

> It's possible that you aren't running with exclusive access

Yes, I'm checking this, which I thought I should have. I just ran `CUDA_VISIBLE_DEVICES=xxx python -m simtk.testInstallation`  in that specific GPU which `somd-freenrg` failed to run, it failed too, it seems like an OpenMM installation problem rather than a Sire specific problem.

**Comment by lohedges** [comment]
Is this an issue with GPU number 7 on all equivalent nodes, or just this one? I wonder if there was a bad job and the GPU has ended up in a funny state, so that it is no longer showing as available.

**Comment by kexul** [comment]
> Is this an issue with GPU number 7 on all equivalent nodes, or just this one?

Just this one.

> I wonder if there was a bad job and the GPU has ended up in a funny state, so that it is no longer showing as available.

Thanks, I'll check that. Currently, I've figured out a temp fix: check GPUs using `testInstallation` and remove bad GPU from my resource queue 🤣.

**Comment by kexul** [comment]
Closing this since it seems not a Sire specific problem, I'll post an update here if I found anything that would benefit the Sire community.

**Comment by YAlhashmi** [comment]
Hi All,

Was this issue resolved? I am still getting the same issue for a relatively small system of 1500 waters. I am running CUDA 11.5, OPENMM 7.6 . Below is my simple script

from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout
import numpy as np

# create force field object:
ff = ForceField('./amoeba2009_plus.xml')

# topology
pdb = PDBFile('bulk.pdb')

# build a simulation system from topology and force field:
system = ff.createSystem(
    pdb.topology,
    nonbondedMethod=PME,
    nonbondedCutoff=0.9*nanometer,
    vdwCutoff=0.9*nanometer,
    ewaldErrorTolerance=1e-5,
    polarisation='mutual',
    mutualInducedTargetEpsilon=1e-5,
    constraints=None,
    rigidWater=False,
    removeCMMotion=True)

# fix switching function
for force in system.getForces():
    if isinstance(force, openmm.NonbondedForce):
        force.setUseSwitchingFunction(True)
        force.setSwitchingDistance(0.1*nanometer)
        
# defining the groups of forces
for force in system.getForces():
    if isinstance(force, AmoebaMultipoleForce) or isinstance(force, AmoebaVdwForce) or isinstance(force, AmoebaGeneralizedKirkwoodForce):
        force.setForceGroup(1)

# integrator
integrator = LangevinIntegrator(298.15*kelvin, 10/picoseconds, 1.0*femtoseconds)
barostat = MonteCarloBarostat(1*bar,298.15*kelvin,50)
system.addForce(barostat)

# prepare a simulation from topology, system, and integrator and set initial positions as in PDB file:
simulation = Simulation(pdb.topology, system, integrator, Platform.getPlatformByName('CUDA'), platformProperties={'Precision':'mixed'})
simulation.context.setPositions(pdb.positions)

# minimization
simulation.minimizeEnergy()

# velocity generation
simulation.context.setVelocitiesToTemperature(298.15*kelvin)

# output information
simulation.reporters.append(DCDReporter('npt.dcd', 500))

simulation.reporters.append(StateDataReporter('run.log', 500, step=True, temperature=True, potentialEnergy=True, kineticEnergy=True, volume=True, density=True, totalEnergy=True, speed=True))

# run over different pressures

simulation.step(2000000)
simulation.saveCheckpoint('restart.ck')

Please advise
