### ISSUE TITLE
Error compiling program: default_program

### ISSUE THREAD

**Issue by msuruzhon** [michellab/Sire#375]
Hello,

I have been testing SOMD on a range of systems, and in some cases, I get the following strange error:

```
RuntimeError: Error compiling program: default_program(14381): warning #177-D: variable "bondParams3" was declared but never referenced
```

Note that I only observe this error when I use `CUDA` and not `CPU`. I am [attaching](https://github.com/michellab/Sire/files/8323497/Archive.zip) a simple system of a perturbed ligand in vacuum to reproduce the error. So far I haven't been able to find out more about this bug but I will let you know if I do.

Cheers.

**Comment by lohedges** [comment]
Thanks for reporting, I think I've also seen something like this. Previously it was the result of writing all terms, even if there were no matching perturbations, i.e. the variable was unused. It's annoying that it only triggers a _warning_ but this is being elevated to an _error_ somewhere. (I guess this is used to make sure that the user is doing what they intend.)

I'll check the terms in your example to see if there's anything obvious. From poking around previous OpenMM issues it looks like it could be due to a mismatch in the CUDA toolkit and driver versions, e.g. [here](https://github.com/openmm/openmm/issues/1925). I wonder if this could be a problem with using the conda-forge OpenMM variant, which is built against the conda-forge tookit. (The Omnia version had a range of driver/toolkit versions, so you could pick the matching one using their channel labels.)

**Comment by lohedges** [comment]
Looking at your output file, this is the actual error:

```
default_program(686): Error: Formal parameter space overflowed (4372 bytes required, max 4096 bytes allowed) in function computeBondedForces
```

It looks like the perturbation might be too large to fit in GPU memory. I've seen this previously when I accidentally included terms in the perturbation that didn't change between the end stages.

For reference, I see the exact same thing on my laptop, using CUDA 11.6.1-1.

**Comment by lohedges** [comment]
This is the tally of the records in the pert file:

- atom = 50
- bond = 20
- angle = 39
- dihedral = 157
- improper = 10

**Comment by lohedges** [comment]
Re-running the script, it looks like the ligand only contains 50 atoms, so _all_ atoms are changing in some way between the end states. (Not necessarily type, but could be charge or LJ terms.)

```python
system = pickle.load(open("Merged_ligand.s3", "rb"))

print(system[0])
import sys
sys.exit()
```

Gives:

```
<BioSimSpace.Molecule: nAtoms=50, nResidues=1>
```

**Comment by msuruzhon** [comment]
Thanks @lohedges this does explain the strange errors. I think that perturbing all of the ligand charges is a fairly normal use case, because most of these perturbations are rather small (there are often small differences in charges even between similar ligands). Is this an intended limitation of SOMD? In which case, how would it be possible to run such systems using SOMD?

Cheers.

**Comment by lohedges** [comment]
I imagine it's the number of bonded terms, particularly dihedrals, that is causing the issue. I don't think it's an intended limitation of SOMD. The perturbation could basically be anything that you like (whether that's sensible, is another matter) but there are clearly memory limitations on the GPU that are limiting the size of what's possible. Ideally we would be able to know the memory limits ahead of time, then raise an exception if things are too large at the time the perturbation file is being written. (Rather than OpenMM failing at run time.) However, I imagine that this would require knowledge of the actual GPU that is in use. (I guess this could be queried at run-time.)

Perhaps @jmichel80 can comment on the size of perturbation that is generally safe to use? I imagine that there could be strategies to split a large perturbation into multiple steps, e.g. by going via an intermediate. Also, If we could set sensible bounds for the number of terms that we can support, then we can warn the user that it may not run.

**Comment by jmichel80** [comment]
Usually all atoms are perturbed as atomic partial charges vary across the whole molecule between pairs of related ligand (often by a tiny amount for atoms far away from a perturbation site). 
The number of perturbed bonds/angles/dihedrals is very large, normally I don't recommend perturbations that change internal degrees of freedom of more than 8-10 heavy atoms. A good rule of thumb is to count the number of atoms that have a chance in amber type. 
Miro if you can post a 2D sketch of the initial /final molecules I can advise on how the perturbation could be broken down into intermediate steps. 
Of course it is possible that the perturbation is not what you intended due to a bug or a mistake.

**Comment by lohedges** [comment]
I count 31 changes in `ambertype`.

```python
system = pickle.load(open("Merged_ligand.s3", "rb"))
mol = system[0]._sire_object

num_changes = 0
for a0, a1 in zip(mol.property("ambertype0").toVector(), mol.property("ambertype1").toVector()):
    if a0 != a1:
        print(a0, a1)
        num_changes += 1

print(f"\nNumber of changes = {num_changes}")
```

Gives:

```
C1 du
C2 N1
Cl1 C1
H1 H5
H1 H5
H1 H5
H2 H4
H2 H4
H3 du
H3 du
H3 du
H4 H3
H4 H3
H4 H3
H4 H2
H4 du
H4 H2
H4 H3
H4 H3
H2 H4
du C1
du C1
du C1
du H1
du H1
du H1
du H1
du H1
du H1
du H1
du H1

Number of changes = 31
```

**Comment by jmichel80** [comment]
Actually looking the perturbation appears to be a -methyl to -cyclopropyl change. @JenkeScheen and @annamherz have done these types of perturbations routinely (in e.g. TYK2). There is also a Ar-Cl to Ar-CH3 perturbation on a phenyl ring and a change of heterocycle. Probably this alltogether exceeds memory limits in OpenMM. 

- I would break this perturbation in different intermediates which should improve convergence. 

I think there is scope to optimise our pert file format to decrease memory footprint. We write by default bond/angle perturbations that include dummy atoms. This was (if I recall) done for debugging purposes. See e.g. 

```
    bond
        atom0          C15
        atom1          H35
        initial_force  397.25458
        initial_equil  1.08536
        final_force    397.25458
        final_equil    1.08536
    endbond
```

Provided the initial_force and initial_equil parameters for this bond are in the input prm7 file then it is not necessary to include this term in the pert file. Removing these would help increase the size of the perturbation that can be processed by SOMD. This would require some testing of course.

**Comment by lohedges** [comment]
Yes, I think you're correct, i.e. we write all bonded terms for atoms involving dummies, even if the terms themselves don't change, e.g.:

```python
# Only write record if the bond parameters change, or involves a dummy.
if has_dummy or amber_bond0 != amber_bond1:
    ...
```

I imagine removing the `has_dummy` conditional would compress the file a lot. I'll see what difference it makes. We could always add this as an option, rather than it being the default.

**Comment by lohedges** [comment]
Actually, I think it's a bit more complicated since, when dummy atoms are present, we are actually modifying the bonded parameters with regards to what is written in the prm7 topology file. For example, if a dummy is present in the lambda=0 state, then we would use the bonded terms from the lambda=1 state, and vice-versa. I _think_ this means that we only need to write terms when they change, or when a dummy atom is present in the lambda=0 state _and_ the terms differ in the lambda=1 state (otherwise we could just go with what is in the topology file).

**Comment by jmichel80** [comment]
Yes we only need to write bond/angle terms when they change, but have to make sure we have a bonded term defined in the prm7 file for degree of freedoms involving dummy atoms. This is because it isn't possible to zero a harmonic potential term (the free energy change for perturbing a harmonic oscillator is -kT ln (k2/k1) where k_i is the initial/final force constant. ) 
By contrast dihedrals involving dummy atoms can be zeroed in the dummy state or kept at their initial parameter safely.

**Comment by JenkeScheen** [comment]
I recently ran some tests on the Amber-TI CatS inputs and had this error in about 20% of cases. Makes sense because in that set the perturbations get quite large as there are many different R-group sites on the main scaffold.

**Comment by mark-cresset** [comment]
Cancel my earlier comment - looks like our problem is due to a bug.
