### ISSUE TITLE
Atomtypes with the sames name but different parameters are not preserved during merge

### ISSUE THREAD

**Issue by msuruzhon** [michellab/Sire#382]
Hi,

I have discovered an issue, where if one tries to merge two molecules which have common atomtype names but different associated parameters, the parameters of the second molecule effectively get lost during writing out.

For example, let the first atomtype be as follows (as taken from a GROMACS top file):
```
H           1    1.007940    0.000000       A    0.500000    0.400000
```

and the second atomtype be as follows:
```    
H           1    1.007940    0.000000       A    0.300000    0.600000
```

The resulting merged topology only has the following definitions:
```
     H           1    1.007940    0.000000       A    0.500000    0.400000
  H_du           0    0.000000    0.000000       A    0.000000    0.000000
```

Files to reproduce this behaviour can be found [here](https://github.com/michellab/BioSimSpace/files/8630571/Archive.zip).

This is a problem that shouldn't occur when one uses GAFF, because of the strict atom type names. However, OpenFF doesn't have canonical atom type names, so an `H1` in one molecule will not in general be the same as an `H1` in another molecule. I think we need to figure out how to uniquify the atom types of the two molecules if they have different parameters but the same name.

**Comment by lohedges** [comment]
I've just pushed a potential fix that renames types if the name matches an existing type but the parameters differ. This is done in the topology writer only, so the properties in the original system will remain unchanged. It resolves the issue for the minimal example that you've provided, but I'm not sure if there's anything else that I might have overlooked. If you could test it out when you get a chance, that would be great. (Perhaps there are other naming issues with OpenFF that we need to be careful with.)

To test, you should only need to update the Sire development package once the build has finished:

```
conda update -c conda-forge -c michellab/label/dev sire
```

(BioSimSpace remains unchanged, hence why I transferred the issue here.)

Cheers.

**Comment by msuruzhon** [comment]
Many thanks for that @lohedges , I will let you know if I find any other issues.

**Comment by lohedges** [comment]
I've just run a quick test combining two OpenFF molecules and it's not quite working as expected. (More atom types are generated than necessary.) Will try to figure out what I've done wrong and will push a fix.

**Comment by lohedges** [comment]
Okay, I _think_ this is working now. It was more complicated than I thought since it wasn't just a case of creating a new type if there was an existing type with the same name and different parameters, i.e. an `H1` in one molecule having different LJ parameters to an `H1` in another. It turns out that an atom type in one molecule might actually match an _existing_ type in the other, so there is no need to create a new type, just re-use the one that it maps to, e.g. just updating the type names. For instance, an `H1` in one molecule might actually have the same parameters as, say, an `H2` in the other.

I've also added a test in BioSimSpace that creates two OpenFF parameterised molecules, translates one of them so that they are sufficiently far apart so they don't interact, then creates a combined system. I then check that the sum of the single point energies for the two molecules in isolation is the same as that of the composite system. This fails prior to my fix  (one molecule has incorrect parameters for one of the atom types), but works following it.
