### ISSUE TITLE
Wrong signs when using Sire.Units.e_charge

### ISSUE THREAD

**Issue by msuruzhon** [michellab/Sire#394]
Hi,

I have discovered some strange behaviour of `Sire.Units.e_charge`, where the sign of the charge can not be set correctly from python. Some examples:

```python
>>> -1 * e_charge
1 |e|

>>> -1 * (-1 * e_charge)
-1 |e|

>>> -1 * (1 * e_charge)
1 |e|
```

I haven't tested if this affects other units.

Many thanks.

**Comment by lohedges** [comment]
Thanks, I'll see if anything else is affected. The BioSimSpace wrapped charge unit behaves correctly, though:

```python
import BioSimSpace as BSS

-1 * BSS.Units.Charge.electron_charge
-1.0000 |e|
```

It also works correctly if you go via a `GeneralUnit`, which simply uses a hardened `eval` in the namespace of `Sire.Units`, then casts to the correct BioSimSpace type depending on the dimensions, e.g.:

```python
BSS.Types._GeneralUnit("-1 * e_charge")
-1.0000 |e|
```

I think this must be because I decouple the value from the unit and store them separately.

**Comment by lohedges** [comment]
Ah, this is because the sign of the electron charge is negative to begin with, i.e.:

```python
e_charge
-1 |e|
```
Hence, multiplying by -1 gives a positive value. I recall that this tripped me up when writing the BioSimSpace units wrappers. I think I was explicit in the definition (somewhere) that `electron_charge` refers to the _absolute_ value.
