### ISSUE TITLE
Variable alchemical value

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#4]
Is there a reason why the alchemical value is set like this:
```
void OpenMMFrEnergyST::setAlchemical_value(double lambda_value){

    Alchemical_value = max(0.0,min(1.0,lambda_value));

}
```
if lambda is between 0 and 1, then why is this max min notation used here?

**Comment by jmichel80** [comment]
Sounds reasonable to protect the code from a user passing a weird lambda
value. The rest of the code only makes sense if lamba is between [0..1].

It would be useful though to print a warning if the code changes the value
passed.

- - -
Julien
Sent from my phone.
On 15 Apr 2015 19:21, "ppxasjsm" <notifications@github.com> wrote:

> Is there a reason why the alchemical value is set like this:
>
> void OpenMMFrEnergyST::setAlchemical_value(double lambda_value){
>
>     Alchemical_value = max(0.0,min(1.0,lambda_value));
>
> }
>
> if lambda is between 0 and 1, then why is this max min notation used here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/4>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
But should something like this not be captured as bad input on the python level ideally? Because otherwise you end up running a simulation you think is valid, that is in fact either 0 or 1, you either simulate the initial or target state.

**Comment by jmichel80** [comment]
Yes but someone could write someday a program that uses directly the C++
API.

There are different viewpoints here but my thinking is that what is going
on in C++ should be 'low-level' and that deciding whether or not to
terminate a script due to unusual input should be 'high-level' and handled
in python.

So one solution could be to:

issue a warning in C++ (could be raising an exception of a return code)
have python code able to catch a warning and decide whether to terminate
the script at this layer of the code.





--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

On Thu, Apr 16, 2015 at 9:25 AM, ppxasjsm <notifications@github.com> wrote:

> But should something like this not be captured as bad input on the python
> level ideally? Because otherwise you end up running a simulation you think
> is valid, that is in fact either 0 or 1, you either simulate the initial or
> target state.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/4#issuecomment-93676622>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
Done.
