### ISSUE TITLE
Unable to set velocity property at the atom level

### ISSUE THREAD

**Issue by lohedges** [michellab/Sire#407]
Prior to Sire 2023.0.0 it was possible to set velocity properties at the atomic level. This is no longer working and is causing molecule merging functionality to fail in BioSimSpace whenever velocities are present. The property can still be set without issue at the molecule level.

```python
import sire as sr

system = sr.load("ejm31*")

# Setting the velocity property for an entire molecule works.
system[0].edit().set_property("test", system[0].property("velocity"))
Editor{ Molecule( MOL:2   num_atoms=32 num_residues=1 ) }

# Trying to set the velocity property at the atom level fails.
system[0][0].edit().set_property("test", system[0][0].property("velocity"))
...
TypeError: Unable to wrap type <class 'sire.legacy.Mol._Mol.Velocity3D'>: ( 1.2359e-06 angstrom fs-1, -1.71641e-05 angstrom fs-1, -1.96013e-05 angstrom fs-1 ) : Python argument types in
    Velocity3D.typeName(Velocity3D)
did not match C++ signature:
    typeName(void)
```

(Example input files [here](https://github.com/michellab/Sire/files/9715110/files.tar.gz).)

**Comment by chryswoods** [comment]
Thanks - this looks like `typeName` being incorrectly wrapped as a standard method, and not as a static method as needed. I will take a look and will fix it.

**Comment by chryswoods** [comment]
Ok - I have worked out the fix. The problem was that you don't call static Py++ functions on the object, but instead only from the class. So,

```
velocity = Velocity3D()
velocity.typename()
```

raises an exception, as `typename` is a static function. It should be

```
Velocity3D.typename()
```

or

```
velocity.__class__.typename()
```

The `typename` function was being incorrectly called by the `__get_typename__` function in `wrapper/Mol/__init__.py`.

```
def __get_typename__(obj):
    try:
        if hasattr(obj, "_to_cpp_type"):
            typename = obj._to_cpp_type().replace("::","_")
        elif hasattr(obj, "what"):
            typename = obj.what().replace("::","_")
        elif hasattr(obj, "typename"):
            typename = obj.typename().replace("::","_")
        else:
            typename = obj.typeName().replace("::","_")

        return (_typename_mapping.get(typename, typename), obj)
    except Exception as e:
        if isinstance(obj, float):
            return ("double", obj)
        elif isinstance(obj, int):
            return ("qint64", obj)
        elif isinstance(obj, str):
            return ("QString", obj)
        else:
            raise TypeError(f"Unable to wrap type {type(obj)}: {obj} : {e}")
```

The fix is to change `obj.typename()` to `obj.__class__.typename()`, e.g.

```
def __get_typename__(obj):
    try:
        if hasattr(obj, "_to_cpp_type"):
            typename = obj._to_cpp_type().replace("::","_")
        elif hasattr(obj, "what"):
            typename = obj.what().replace("::","_")
        elif hasattr(obj, "typename"):
            typename = obj.__class__.typename().replace("::","_")
        else:
            typename = obj.__class__.typeName().replace("::","_")

        return (_typename_mapping.get(typename, typename), obj)
    except Exception as e:
        if isinstance(obj, float):
            return ("double", obj)
        elif isinstance(obj, int):
            return ("qint64", obj)
        elif isinstance(obj, str):
            return ("QString", obj)
        else:
            raise TypeError(f"Unable to wrap type {type(obj)}: {obj} : {e}")
```

A bigger question us why this bug hasn't popped up before. On digging, it is because the `typename` branch of the `if` statement is only called if the class is missing a `what()` function. (this function can be called from the object, and calls the `typename()` function correctly)

Nearly all sire objects have both a `what()` and a `typename()` function, and so this bug wasn't exposed. For some reason, I had not added a `what()` function to [`Vector3D<T>`](https://github.com/michellab/Sire/blob/devel/corelib/src/libs/SireMaths/vector3d.hpp). So a double-fix is to add the `what()` function and to regenerate the wrappers (regenerated in `Mol` as this is where `Velocity3D` is instantiated).

I've made this change in [this commit](https://github.com/michellab/Sire/commit/44780a97d9859e94b7a7fc349a8e94b48a6505a8) in the `feat_2023_0` branch. The delta could be merged into `devel`. Or, as the partial (but working) fix is just the change in `Mol/__init__.py` this could be manually added to `devel`.

Thanks for the bug report - this is a very subtle bug which was a lot of fun to track down and squash :-)

**Comment by lohedges** [comment]
Thanks for getting to the bottom of this. I've just patched the diff from `Mol/__init__.py` into `devel` and can confirm that everything is working as expected.
