### ISSUE TITLE
cmake files and bundeling

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#53]
There is a lot of old/redundant information in the makefiles. (Such as svn version, which isn't event used anymore). This should be tidied up soon.

Furthermore some of the bundeling done is really clunky and it is difficult to add new repositories to. 
In the particular case I would like to add a dependency for pymbar to the repository, which requires also a dependency of numpy and six. The latter two can be installed via pypi, pymbar cannot, or at least not a python3 supported version of it. 

I would temporarily propose to replace the python3 zip with a miniconda installation. This can be downloaded online, on the fly, allowing always for the latest version, the installer is small and fast, making the repository more managable. 
I had a little look at it, but since my knowledge of cmake is very limited, I couldn't quickly figure out how to do this, without breaking anything. 

Naively I assumed it should be something like this:
```
execute_process(
  COMMAND ${CMAKE_COMMAND} -E wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
)
execute_process(
  COMMAND ${CMAKE_COMMAND} -E bash miniconda.sh -b -p ${BUNDLE_BUILDDIR}/miniconda
)
execute_process(
  COMMAND ${CMAKE_COMMAND} -E ${BUNDLE_BUILDDIR}/miniconda3/bin/conda install numpy scipy 
)
```
It clearly doesn't just work replacing the python installation with the above (or probably it does but I am missing some important bits here and there). I would probably waste quite some time to figure out, how to make a miniconda installation work as the bundled python does at the moment. It would be great if I could have some feedback/help with this.

**Comment by ppxasjsm** [comment]
And it gets worse...I forgot there was a scipy dependency which is a nightmare to install with pip.

**Comment by chryswoods** [comment]
I agree - this is a very messy problem. I like your idea of downloading a miniconda distribution and using this instead of compiling our own Python. The Python wrappers in Sire can be compiled for Python 2 or Python 3, so maybe there is an argument that we should switch back to Python 2 to support miniconda? (or allow both Python 2 and Python 3 versions to be compiled, thereby allowing people to choose which one they want to use based on which other Python modules they are using?)

The cmake files are "clunky" with repetition because it is very difficult to get cmake to do what we need it to do. Naively I would assume that your cmake above should work to download and install miniconda, but it doesn't. Also, you haven't accounted for different operating systems and platforms, e.g. you need to use the cmake code to detect the processor and operating system, and then map this to the right miniconda distribution to download.

My suggestion is that we use cmake only download and install miniconda, and then write a python script that installs all of the other python dependencies, based on what the user has requested. The Python script will be run using the miniconda that has been downloaded, and we can then use that python script to control all of the dependencies and handle all of the errors etc. (e.g. if pip fails, or a network isn't available, or if the install fails). Also, the python script that installs the dependencies should run quick tests to ensure that the dependencies have installed correctly.

**Comment by jmichel80** [comment]
Supporting python2 and 3 would be a nightmare since python3 is not backwards compatible, we may have to write two sets of python scripts for each app. I'd rather stick to python3 at this stage. 

I haven't used miniconda but this link 
http://conda.pydata.org/miniconda.html

suggests that it is possible to use python3. 

I like your idea to have a minimal cmake and then control the rest of the python install via a python script. Sounds less horrible.

**Comment by chryswoods** [comment]
Python 2 and Python 3 are much more compatible then you think. By using __future__ I have found it very easy to write Python scripts that work in both 2 and 3, and all of my Python teaching is agnostic to whether python 2 or 3 are used. The Python 2to3 tool is also great at converting scripts, and is a good starting point to writing something more complex that should be compatible with both.

I agree that I would prefer to stick with Python 3 as it is the future, and increasingly the present. However, if you have dependencies that are Python 2 only, then it is worth knowing that Sire can be compiled to support Python 2.

**Comment by ppxasjsm** [comment]
Module called six (2*3) is also great for developing for both python 2+3! I think supporting both shouldn't be that difficult. 
There are no python2 only dependencies. Just old versions of the dependencies on pip are python2 only.

**Comment by ppxasjsm** [comment]
Also miniconda lets you set different environments that can be either python2 or 3 and have various different things installed within these environments to test stuff for example. 
@chryswoods, indeed I haven't actually checked for different os, but the same installer exists for macosx. The above code was more some kind of pseudo code for me trying to figure out if this makes sense. I am also happy to help with this, but I think I need quite some detailed instructions, since I find it difficult to find my way around the current set of make files, and probably end up breaking things more than fixing them!

**Comment by chryswoods** [comment]
Ok - I've compiled corelib and the wrappers from devel github, and they all compile and install well. However, none of the Python modules needed for easy_install or pip install correctly because of problems with Python 3.3 and Yosemite. I fixed these in google code by switching to Python 3.4. Do you want me to make this change here, or do you think we should see if we can get the miniconda solution to work?

**Comment by ppxasjsm** [comment]
I think the miniconda solution would be better make all installation alot easier since we will have both conda and pip repositories available to us and of course python 3.4.

**Comment by ppxasjsm** [comment]
I would also be interested managing to compile on a Mac, I gave up in the end because I had spend to much time compiling and a virtual machine works just fine.

**Comment by chryswoods** [comment]
Ok - I think we are agreed that we should try the miniconda solution. I will try to get this working over the next day and will let you know how I get on. I will download miniconda and see if I can get it working on my mac (by far the hardest platform to get working portably - but admittedly easier than windows!). I suspect that the biggest issue will be sorting out @rpath.

**Comment by ppxasjsm** [comment]
Getting conda to work on a Mac should be easy, with Sire...no idea. If I can help in anyway let me know.

**Comment by ppxasjsm** [comment]
And thanks for helping with this!

**Comment by chryswoods** [comment]
Closing as now dealt with in another thread, and code implemented
