### ISSUE TITLE
Obscure bug in SireMM::FourAtomPerturbation::perturbMolecule and possible fix ?

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#59]
Hi, 

I'm puzzled by a strange behaviour of Sire that I have discovered while debugging energies of single topology morphs that have variable impropers. 

I'm working with a setup where I am morphing acetone into propane.  The topology is, using acetone as a starting state:

```
     O3
     |
```

C1-C2-C4
         |
         DU11

Leap adds to the parm file an  improper term for impropers involving the carbonyl group and the dummy atom, i.e.

C1 DU11 C2 O3
C4 DU11 C2 O3

These get assigned the potential 10.5 \* ( 1 + cos ( 2 phi - pi ) ) 

This leads to an incorrect simulation of acetone at lambda=0.0.

To address this FESetup overrides leap with variable improper definitions in the MORPH.pert file

(...)
        improper
                atom0   C1
                atom1   DU11
                atom2   C2
                atom3   O3
                initial_form 0.0 0.0 0.0 
                final_form 0.0 0.0 0.0 
        endimproper
        improper
                atom0   C4
                atom1   DU11
                atom2   C2
                atom3   O3
                initial_form 0.0 0.0 0.0 
                final_form 0.0 0.0 0.0 
        endimproper
(...)

Now when a free energy calculation would be performed, sire load first an amber parm7 file, and then 'patches' the topology according to the pert file. This should override the wrong leap impropers.

Except Sire only does it only for C1 DU11 C2 C3, so I still end up with a bad improper term for C4 DU11 C2 O3. 

Eventually I realised this happened because of the code in SireMM::FourAtomPerturbation::perturbMolecule 

(...)
    Expression new_function = perturbExpression().substitute(idents);

```
Expression old_function = funcs.potential(atm0, atm1, atm2, atm3);
```

   if (new_property or (new_function != old_function))
    {
        //funcs.set(atm0, atm1, atm2, atm3, new_function);
      // What if this is dealing with impropers?
        funcs.set( DihedralID(atm0, atm1, atm2, atm3), new_function);
        molecule.setProperty(param_property, funcs);
    }

The problem is easier to explain by adding the line of code 
Expression old_function2 = funcs.potential(atm3, atm2, atm1, atm0);
and a few print statements. 

This shows that for these two impropers (listed below by atom indices rather than atom names)

Dihedral  "Dihedral( AtomIdx(3), AtomIdx(10), AtomIdx(1), AtomIdx(2) )" 
new func  "0" 
old func  "0" 
old func2  "10.5 [cos(2 phi - 3.14159) + 1]" 
Dihedral  "Dihedral( AtomIdx(0), AtomIdx(10), AtomIdx(1), AtomIdx(2) )" 
new func  "0" 
old func  "10.5 [cos(2 phi - 3.14159) + 1]" 
old func2  "0"

So in the first case 3 -10-1-2 which corresponds to C4 DU11 C2 O3 the code believes that the new and old potentials are the same because new func and old func are the same. In that case the new function is not applied. 
However this happened because the FourAtomFunction that stores this improper potential is

FourAtomFunction( {CGIdx(0),Index(2)} <- {CGIdx(0),Index(1)} - {CGIdx(0),Index(10)} -> {CGIdx(0),Index(3)} : 10.5 [cos(2 phi - 3.14159) + 1] )

The order of the atoms in FourAtomFunction is the _reverse_ of the order of the atoms in the matching FourAtomPerturbation  

FourAtomPerturbation( AtomIdx(3)-AtomIdx(10)-AtomIdx(1)-AtomIdx(2) : 0 )

By default funcs.potential(atm0, atm1, atm2, atm3) returns a  Expression("0") if no matching FourAtomFunction is found in funcs.  Since the new_function is also Expression("0") then new_function = old_function and the new_function is not set. 

This is why the definition of old_function2 (that has swapped the order of the atoms) returns the expected potential

old func2  "10.5 [cos(2 phi - 3.14159) + 1]" 

This is very strange because the improper in the amber parm7 file and in the pert files are defined in the same order. 

For the other improper  C1 DU11 C2 C3 the code  behaves as expected because the order of the atoms in the molecule's FourAtomFunction is the same as in the molecule's FourAtomPerturbation (because they are in the same order in the parm7 file and the pert file). 

I really don't understand why this improper has changed the order of the atoms ! 

 One kludge that _solves_ the problem is to remove the final if statement, i.e.

```
if (new_property or (new_function != old_function))
{
    //funcs.set(atm0, atm1, atm2, atm3, new_function);
  // What if this is dealing with impropers?
    funcs.set( DihedralID(atm0, atm1, atm2, atm3), new_function);
    molecule.setProperty(param_property, funcs);
}
```

becomes

```
    //funcs.set(atm0, atm1, atm2, atm3, new_function);
  // What if this is dealing with impropers?
    funcs.set( DihedralID(atm0, atm1, atm2, atm3), new_function);
    molecule.setProperty(param_property, funcs);
```

Now the code sets the new_function no matter what. 

Another kludge would be to have
funcs.potential(atm0, atm1, atm2, atm3) not return an Expression("0") if no matching atoms are found.

A better solution would be to figure out why funcs.potential(atm0, atm1, atm2, atm3) does not find the correct potential. I think this would involve looking at SireMM:FourAtomFunctions and figure out what is going on.

**Comment by jmichel80** [comment]
It looks like that replacing
    Expression old_function = funcs.potential(atm0, atm1, atm2, atm3);
by
    Expression old_function = funcs.potential( DihedralID(atm0, atm1, atm2, atm3));
would work since FourAtomFunctions.potential( DihedralID( ....) ) attempts to look up a potential using atm0, atm1, atm2, atm3 and also atm3, atm2, atm1, atm0. 
However if I do this change the code raises a runtimeerror that I do not understand.

Exception 'SireError::program_bug' thrown by the thread 'master:main'.
Constraint PerturbationConstraint( [solutes:6], perturbations ) is not satisfied despite having just been applied!!!
Thrown from FILE: /home/julien/software/devel/git/sire/corelib/src/libs/SireSystem/constraint.cpp, LINE: 164, FUNCTION: bool SireSystem::Constraint::apply(SireSystem::Delta&)

**Comment by chryswoods** [comment]
This is an interesting bug.

Your fix starts to work because funcs.potential( DihedralID(atm0,atm1,atm2,atm3) ) behaves differently to funcs.potential( atm0, atm1, atm2, atm3 ). If you look in the C++ code in fouratomfunctions.cpp you will see that the DihedralID version looks up both atm0,atm1,atm2,atm3 and atm3,atm2,atm1,atm0, while the other version only looks up atm0,atm1,atm2,atm3.

Because the perturbation code uses the atom version, not the DihedralID version, this means that you found a function that is not the one that Sire expects (even though it is the one you want). Because Sire didn't expect this function, the test that checked that the PerturbationConstraint was correctly applied then fails, hence why you get the program_bug exception (program_bug is reserved for errors that indicate a deep logic bug in the code, and that are really program bugs).

Thus your fix is not correct. This is because the order of dihedrals/impropers is important in Sire, and so it does treat atm0,atm1,atm2,atm3 differently to atm3,atm2,atm1,atm0. I seem to remember that this was a deliberate choice to fix an old design problem, where if I automatically mirrored dihedrals/impropers (i.e. said that atm0,atm1,atm2,atm3 is equivalent to atm3,atm2,atm1,atm0) then it prevented the implementation of other algorithms. Thus your fix breaks this assumption of the code, hence resulting in the program bug.

For your other fixes;

(1) Removing the final "if statement" - this again could lead to weird bugs because this would not mirror the "wouldChange" function (wouldChange tells the code whether or not the perturbation will affect the system, and so if wouldChange reports "false" but "perturbMolecule" actually does something (or vice versa) then there is a logical inconsistency that can cause program bugs later in the code.

(2) Changing the lookup function so that Expression(0) is not returned. This would be incorrect, as, but default, any dihedral or improper that does not have a function attached has an energy of 0 (e.g. Expression(0)). If we changed this to be an error, or to return something different than Expression(0), then this will break code higher up that assumes that it can query the potential of any dihedral or improper and that Expression(0) should be returned (as this is logically correct).

Looking deeper into the problem, I think that it is because of the line;

    //funcs.set(atm0, atm1, atm2, atm3, new_function);
  // What if this is dealing with impropers?
    funcs.set( DihedralID(atm0, atm1, atm2, atm3), new_function);
    molecule.setProperty(param_property, funcs);

This is only in your branch of the code. In my branch, I have;

      funcs.set(atm0, atm1, atm2, atm3, new_function);

I don't know why this was changed to use DihedralID rather than just add the function using the atoms. The difference between these two funcs.set functions is that the one I use (atm0,atm1 etc.) only sets the function for that specific order of atoms, while the one using DihedralID first clears the functions for atm0,atm1,atm2,atm3 and atm3,atm2,atm1,atm0, and then sets the function for atm0,atm1,atm2,atm3.

Could you change the code back so that is uses the (atm0,atm1,atm2,atm3) version of funcs.set (i.e. get rid of the DihedralID) and then let me know what happens?

In terms of Dihedrals and Impropers, Sire has no internal knowledge of what a Dihedral or Improper is. All Sire does is assign functions to quads of atoms. Sire doesn't care about the bonding or topology of those four atoms - it just adds in a potential. In reality, BondID, AngleID and DihedralID are misnamed. They are really just the 2-atom, 3-atom and 4-atom equivalents of AtomID.

**Comment by jmichel80** [comment]
Hi Chris, 

I have done as you said. To test what happens I have a script that loads a single topology describing a AtoB perturbation. I minimised the topology at lambda=0.0 and at lambda=1.0 and save the component energies. I do the same for BtoA at lambda=0.0 and lambda=1.0. 
If everything is handled consistently and the minimisation successful, then I must get the same energies (to within minimisation errors)

* Test1) Without any code changes, I get the following results:
all test perturbations give consistent energies, with the exception of 
acetone~propane
acetone~tbutane 
And this is down to the impropers energies discussed previously. 

* Test2) If I just remove the if statement, the only energies that change with respect to test 1are those of acetone~propane and acetone~tbutane and they are now consistent.

* Test3) If I just use funcs.set(atm0, atm1, atm2, atm3, new_function) then some of the molecules in my test set have consistent energies. This is down to discrepancies in dihedral and improper energies. Other terms appear identical. 

* Test4) If I remove the if statement, and use funcs.set( ...) as above. Identical results to test3.

Unfortunately I do not remember why the codes have diverged here. The comment about impropers suggest I did this change while debugging the implementation of the single topology calculations using perturbationslibrary objects. 

Having looked further at the code. I think the swap in atom order happens because in amber.cpp around line 900 we use this code to set improper functions (or dihedral functions)

    for (QHash<DofID,Expression>::const_iterator it = improper_hash.constBegin();
            it != improper_hash.constEnd();
            ++it)
    {
        improperfuncs.set( it.key().atom0(), it.key().atom1(), it.key().atom2(),
                           it.key().atom3(), it.value() );
    }

We are iterating over a QHash of DofID that is build on line 826

            DofID improperid = DofID( atom0.index(), atom1.index(),
                                      atom2.index(), atom3.index() );

            if ( improper_hash.contains(improperid) )
                improper_hash[improperid] += dihedral_func;
            else
                improper_hash.insert(improperid, dihedral_func);

DofID internally orders atom indices. 
I dug up a google chat session  between us (from 2010 ! ) that suggests this was done to speed up the parser. Excerpts below

Christopher: I have changed Flexibility quite a lot  (internally)
 me: when bonds, angles, dihedrals etc..are added//removed
  it should be checked that they are part of molinfo
 Christopher: I have already done this
  I have changed flexibility so that it only stores the QHash<DofID,Length> and QHash<DofID,Angle>
4:38 PM 
And the molinfo object is consulted every time something is added or removed
  I have also changed DofID so that it orders the AtomIdx objects, so that Bond(atom0,atom1) is the same as Bond(atom1,atom0)
  I hope you will like the changes - if you don't understand why I did something please feel free to ask
4:39 PM 
Particularly with amber.cpp/.h
  (which is now about 30% faster)


However the code that applies perturbations is in SireIO::perturbationslibrary::apply_template

There perturbations are not built using DofIDs

e.g. line 446
      FourAtomPerturbation dihedralpert = FourAtomPerturbation( atom0, atom1, atom2,atom3,
								dihedralfunc_i, dihedralfunc_f,
								PropertyMap("parameters", "dihedral") );

Which is why I think there is swap. 

My hypothesis: 
- I coded amber.cpp and perturbationslibrary.cpp
- DofID was then updated. 
- I got confused debugging perturbationslibrary.cpp and introduced the funcs.set(DihedralID(... fix
This would address internally any swap issues since funtions atm0,atm1,atm2,atm3 and atm3,atm2,atm1,atm0 are cleared and then atm0,atm1,atm2.atm3 is set. 

This suggests that a solution is to change the code in SireIO::perturbationslibrary from

      FourAtomPerturbation dihedralpert = FourAtomPerturbation( atom0, atom1, atom2,atom3,
								dihedralfunc_i, dihedralfunc_f,
								PropertyMap("parameters", "dihedral") );

to

      DofID id = DofID(atom0, atom1, atom2, atom3);
     
     FourAtomPerturbation dihedralpert = FourAtomPerturbation( id.atom0(), id.atom1(), id.atom2(), id.atom3(),dihedralfunc_i, dihedralfunc_f,PropertyMap("parameters", "dihedral") );

(and same for improperpert)

* Test5: Having done these code changes, and combined with your proposed code change to internalperturbation.cpp I repeated all calculations 

Unfortunately the energies of most molecules in my test set become inconsistent, so this doesn't seem to be the correct solution. 

If you wish I can email log files and/or input files and scripts to reproduce these results.

**Comment by chryswoods** [comment]
Curious. I am happy that test (3) and test (4) give the same result, as this at least implies that there is consistent ordering, and so the if test is not required (even if the consistent ordering is incorrect in some cases).

The result from test (2) implies that this is an ordering issue, and a fix can be hacked. However, this may cause a weird bug for the future.

Yes, it looks from your work tracking things down that the error has occurred when I added an order independence test (DofID), when everything else is order-dependent. Perhaps the solution is to revert DofID back to being order-dependent? That way, we can know that the order of atoms has meaning in all of the code, i.e. that we can never assume that atm0-atm1-atm2-atm3 == atm3-atm2-atm1-atm0.

Please email me the log files and the input files and scripts so that I can try to run this myself and do some debugging.

**Comment by jmichel80** [comment]
On Fri, Sep 4, 2015 at 3:28 PM, Christopher Woods <notifications@github.com>
wrote:

> Curious. I am happy that test (3) and test (4) give the same result, as
> this at least implies that there is consistent ordering, and so the if test
> is not required (even if the consistent ordering is incorrect in some
> cases).
>
> The result from test (2) implies that this is an ordering issue, and a fix
> can be hacked. However, this may cause a weird bug for the future.
>
> Yes, it looks from your work tracking things down that the error has
> occurred when I added an order independence test (DofID), when everything
> else is order-dependent. Perhaps the solution is to revert DofID back to
> being order-dependent? That way, we can know that the order of atoms has
> meaning in all of the code, i.e. that we can never assume that
> atm0-atm1-atm2-atm3 == atm3-atm2-atm1-atm0.
>
> We would have to be very careful that this doesn't have unexpected
consequences. Code that use to expect to look up dihedrals regardless of
the order in which the atoms are listed may suddenly fail.

Please email me the log files and the input files and scripts so that I can
try to run this myself and do some debugging.

Done

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by chryswoods** [comment]
Closed as fixed in the latest commit of merge_2014_4

**Comment by chryswoods** [comment]
This took a lot of debugging, but eventually the fix was simple. The problem was because of the (undocumented) behaviour difference between looking up things using AtomIDs versus looking up things by DihedralIDs. When looking up by AtomID, you are specifying the order, e.g.

funcs.potential( atm0, atm1, atm2, atm3 )

is allowed to be different to

funs.potential( atm3, atm2, atm1, atm0 )

However, DihedralID has the additional rule that a dihedral is order-independent, i.e.

funs.potential( DihedralID(atm0,atm1,atm2,atm3) )

is constrained to be equal to 

funs.potential( DihedralID(atm3,atm2,atm1,atm0) )

This means that if you want order-independent lookup or setting of dihedral potentials you must use DihedralID rather than four AtomIDs.

I changed FourAtomPerturbation to use DihedralIDs (in both the perturbMolecule and wouldChange functions, as wouldChange runs a test to see if the perturbation still needs to be applied). This now gives identical energies when I run your singlepointenergy.py script. 
==============
moleculeA        moleculeB       lambda  E_{total}       E_{solute_intraff}^{bond}       E_{solute_intraff}^{angle}      E_{solute_intraff}^{dihedral}   E_{solute_intraff}^{improper}   E_{solute_hard_intraclj}^{coulomb}      E_{solute_hard_intraclj}^{LJ}           E_{solute_todummy_intraclj}^{coulomb}   E_{solute_todummy_intraclj}^{LJ}        E_{solute_fromdummy_intraclj}^{coulomb}         E_{solute_fromdummy_intraclj}^{LJ}      E_{solute_hard:fromdummy_intraclj}^{coulomb}    E_{solute_hard:fromdummy_intraclj}^{LJ}         E_{solute_hard:todummy_intraclj}^{coulomb}      E_{solute_hard:todummy_intraclj}^{LJ}   E_{solute_todummy:fromdummy_intraclj}^{coulomb}         E_{solute_todummy:fromdummy_intraclj}^{LJ}
acetone          propane         0.0     -12.54278        0.00470         3.79446         5.26912 
        0.86915        -23.27925        0.79904         0.00000         0.00000         0.00000 
        0.00000                 0.00000         0.00000         0.00000         0.00000         0.00000         0.00000       
TEST: 0.8691525196071604
propane          acetone         1.0     -12.54278        0.00470         3.79446         5.26912 
        0.86915        -23.27925        0.79904         0.00000         0.00000         0.00000 
        0.00000                 0.00000         0.00000         0.00000         0.00000         0.00000         0.00000       
TEST: 0.8691525823942161
acetone          propane         1.0      1.16448         0.01450         0.06119         0.00352 
        0.00000         0.00299         0.28866         0.00000         0.00000         0.00000 
        0.00000                 0.73863         0.05499         0.00000         0.00000         0.00000         0.00000       
TEST: 0.0
propane          acetone         0.0      1.16452         0.01450         0.06114         0.00356 
        0.00000         0.00299         0.28872         0.00000         0.00000         0.00000 
        0.00000                 0.00000         0.00000         0.73863         0.05499         0.00000         0.00000       
TEST: 0.0
=====================

Please could you update your code and check that this works for you, and that it doesn't give weird errors when running a simulation.

**Comment by jmichel80** [comment]
So I finally updated my code. I can reproduce your results.
I will run a few tests over the coming days to check if there are no new strange errors.

**Comment by chryswoods** [comment]
Closing as I assume that this has now been fixed.
