### ISSUE TITLE
Sire with anaconda/miniconda

### ISSUE THREAD

**Issue by chryswoods** [michellab/Sire#60]
I've managed to update the CMakeLists.txt files in corelib and wrapper to build a copy of Sire into an existing miniconda distribution. This will be an additional install route for Sire that will complement the bundled python route.

The way it works is through an option "ANACONDA_BUILD", which when set tells cmake to build Sire for installation into an existing anaconda/miniconda installation. You need to supply "ANACONDA_BASE" to tell cmake where anaconda is installed, e.g. "${HOME}/miniconda3".

At the moment, the core is all compiled and built into miniconda3/pkgs/sire-0.0.1, with the Sire modules installed into miniconda3/lib/python-X.X/site-packages. I have to do some work with library paths ($ORIGIN and @rpath) as I have to copy all libraries from miniconda3/pkgs/sire-0.0.1/lib and miniconda3/pkgs/sire-0.0.1/bundled/lib into miniconda3/lib to get this to work.

I have some questions before I proceed with this and commit it to git:

(1) Do you think this is the right way to go? Does it cause issue with what you are doing? 

(2) At the moment, Sire uses its own python binary. This is to handle multithreading, clusters and various tricks to allow symbolic links to the python executable to auto-route to python scripts. I think that I will need to change this so that Sire creates a sire_python executable in miniconda3/bin, and then the symbolic links can link to sire_python (and also then go into miniconda3/bin). Does this sound sensible?

(3) I think that we can turn the miniconda3/pkgs/sire-0.0.1 directory into a portable binary install, as we have for sire.app. If that is the case, do you think that it is worth putting in the effort to do this? We could then have "pip install sire" just download the correct binary that is unpacked into pkgs/sire-0.0.1.

(4) The end result of this is that people will be downloading/compiling Sire into existing installations of anaconda/miniconda. This is desirable, as it should make it easier to get Sire to work with other packages. However, do you foresee any maintenance headaches of this approach?

**Comment by chryswoods** [comment]
I've just pushed my changes into devel. They should not change anything that exists already. Instead, they add the option of building into an existing anaconda/miniconda download. Full instructions are given in the INSTALL_INTO_ANACONDA_README in the top level directory. This has been tested on Linux. I am going to have to do some more work to get this working with OS X. I also haven't yet updated the package_sire command, which I will need to do to allow correct packaging of Sire.

**Comment by jmichel80** [comment]
That's great ! I will try to find a bit of time to look at this in details next week while I am traveling. 
Antonia should have a better idea than me about the pro/cons of a Sire anaconda integration so I will let her comment on your questions.

**Comment by ppxasjsm** [comment]
I will try and reply to your questions to the best of my knowledge.

(1) Installing Sire into an existing python distribution, such as anaconda is for sure desirable and I think it is the right way to go. I see one issue which might arise. If Sire stays at version 0.0.1 it will become confusing quickly for people what version of the library they are using. Updates from a previous installation would overwrite the original installation and reproducibility of results with exact versions seems not obvious to me hot to achieve this. 

(2) I have not looked into how the symbolic linking is done with Sire and how the command line based tools are run/linked. Maybe I don't quite understand all the trickiness involved here. So ~/miniconda/bin/ would contain all the command line tools, such as somd/waterswap, etc? But also contain a python executable ~/miniconda/bin/sire_python, which can then be used to run custom Sire python scripts?

(3) I have no idea how complicated it is to turn the installation into a binary. I know there are automatic packaging tools for pip, which allow for release tags to be automatically packaged and pushed to pypi. If something like that worked that would be great!

(4) Generally installing this into conda is a good idea, however this should be done the conda way using conda recipes (http://conda.pydata.org/docs/building/recipe.html), rather than just using the python conda directory structure. If this is done the conda way then I expect maintenance to be minimal doing it not the conda way probably can provide to be a headache, but I have little experience here too. 

I hope this feedback helps a little bit.

**Comment by chryswoods** [comment]
Thanks. I've now updated so that the cmake config will auto detect and link to the OpenMM installation in conda if it has been installed. I've updated the install instructions with details of how to compile and link with OpenMM

I've now sorted out (1)-(3) and yes, there is now a miniconda/bin/sire_python to which all of the scripts are linked. There is also the normal conda bin/python, which can also be used to run the scripts as you would normally, e.g. bin/python share/Sire/scripts/somd.py

I agree that we should use the conda recipe as much as possible. I have been reading up on all of this over the last week and have been trying to see how we will fit in. My route so far has respected the conda directory structure and has most of what is needed. From what I can see, what is left is to add a hook into the conda build recipe to either invoke the cmake scripts to build Sire, or to download the pre-compiled libraries and put them in the right place. I will play with this at a later date as it is not urgent (it is much more urgent now that I work out how to update your git branch to match Sire 2014.4, as it is currently back at Sire 2014.2... I will do this work in a fork and will then issue a pull request to pull this in).

Finally, I agree that I will need to update the Sire version number and 0.0.1 is not appropriate. I will update this number to a "2015.1" type value so that we will have conda/pkgs/sire-2015.1 as the install directory.

**Comment by ppxasjsm** [comment]
Have a look at __init__.py. I have implemented a version there that would be identical to the tags used later for the release. I would use 3 digits. 2015.1.0, which allows bug fix patches and not forcing a new 'release'.

**Comment by ppxasjsm** [comment]
And thanks for the updating of the updating to 2014.4!

**Comment by chryswoods** [comment]
No problem. The updating to 2014.4 may take a week or so...

Yes, what you have done in __init__.py looks good. I will integrate this with the cmake scripts so that we just have to set a version once and then it will be placed in all places where it needs to be (e.g. available to query from Sire.Base, attached to the C++ libraries etc.)

**Comment by chryswoods** [comment]
I've now completed the merge and made a pull request. Closing here as conversation should now move to the pull request.
